(function(C){C.execute(function(){(function(e){document.createElement("header");var a=function(b){function d(a,b,d){a[d]=function(){c._replay.push(b.concat({m:d,a:[].slice.call(arguments)}))}}var c={};c._sourceName=b;c._replay=[];c.getNow=function(a,b){return b};c.when=function(){var a=[{m:"when",a:[].slice.call(arguments)}],b={};d(b,a,"run");d(b,a,"declare");d(b,a,"publish");d(b,a,"build");return b};d(c,[],"declare");d(c,[],"build");d(c,[],"publish");d(c,[],"importEvent");a._shims.push(c);return c};
a._shims=[];if(!e.$Nav)e.$Nav=a("rcx-nav");if(!e.$Nav.make)e.$Nav.make=a})(window)})})(function(){var C=window.AmazonUIPageJS||P,e=C.attributeErrors;return e?e("NavAuiShim"):C}());
/* ******** */
(function(y,h,q){y.execute(function(){function o(c){function a(){var a=Date.now();return{uid:a,suggestionsReadyForDisplay:{name:"suggestionsReadyForDisplay-"+a},suggestionsReady:{name:"suggestionsReady-"+a},suggestionsRendered:{name:"suggestionsRendered-"+a},updateSearchBox:{name:"updateSearchBox-"+a},selectionChange:{name:"selectionChange-"+a},dropdownHidden:{name:"dropdownHidden-"+a},updateSearchTerm:{name:"updateSearchTerm-"+a},suggestionClicked:{name:"suggestionClicked-"+a},suggestionsNeeded:{name:"suggestionsNeeded-"+
a},a9SuggestionsNeeded:{name:"a9-suggestionsNeeded-"+a},noSuggestions:{name:"nosuggestions-"+a},searchBoxFocusIn:{name:"searchBoxFocusIn-"+a},searchBoxFocusOut:{name:"searchBoxFocusOut-"+a},keydown:{name:"keydown-"+a},hideDropdown:{name:"hidedropdown-"+a},focusOnParent:{name:"focusOnParent-"+a},parentFocused:{name:"parentFocused-"+a},parentLostFocus:{name:"parentLostFocus-"+a},searchTermChanged:{name:"searchTermChanged-"+a},suggestionsDisplayed:{name:"suggestionsDisplayed-"+a},upArrowPressed:{name:"upArrowPressed-"+
a},downArrowPressed:{name:"downArrowPressed-"+a}}}return{globals:{issLoaded:{name:"issLoaded"},suggestionsRendered:{name:"suggestionsRendered"},initializeNavSearchBox:{name:"initializeSearchBox"}},createInstance:function(){return new a},createEvent:function(a,g){var e=g;g.hasOwnProperty("name")?e=g.name:typeof g==="string"?e=g:c.logDebug('Format of "event" parameter is not a string or an event object',g);return a+"-"+e}}}h.$Nav.when("$","nav.inline").run(function(c){h.$Nav.declare("config.blackbelt",
c("#nav-belt").length>0)});h.$Nav.when("config.blackbelt").run(function(c){c?h.$Nav.when("searchApi").run(function(a){h.$Nav.declare("sxSearchApi",a)}):h.$Nav.declare("sxSearchApi")});h.$Nav.when("$","sxSearchApi","sx.iss.DomUtils").build("NavDomApi",function(c,a,b){var g,e,j;function i(){return r?l().find('input[type="text"]'):(typeof p==="undefined"&&(p=c(g)),p)}function d(){return r?a.flyout.elem():(typeof o==="undefined"&&(o=c(s),l().after(o)),o)}function f(){return r?a.options().parents("select"):
(typeof x==="undefined"&&(x=c(e)),x)}function l(){return r?a.options().parents("form"):c(j)}function k(){var a=n(),b=d();d().is(":visible")&&!(b.html().length<1)&&b.css({left:a.offset().left,width:a.width()})}function n(){w===q&&(w=c("#nav-iss-attach"));return w}var r=a!==q;g="#twotabsearchtextbox";e="#searchDropdownBox";j="#nav-searchbar";var p,m,o,x,w,s='<div id="search-dropdown" class="search-dropdown"></div>',u=/search-alias\s*=\s*([\w-]+)/;a===q&&c(h).resize(k);return{getAliasDropdown:f,getSearchBox:i,
getSearchBoxId:function(){return g},getSearcchSuggestions:function(){typeof m==="undefined"&&(m=c("#srch_sggst"));return m},getKeyword:function(){var d;d=a!==q?a:i();return b.getKeyword(d)},setKeyword:function(b){if(a!==q)a.val(b);else return i().val(b)},getAliasFromDropdown:function(){var a=f().val();return(a=a&&a.match(u))?a[1]:q},getCategoryNameFromDropdown:function(a){var b="";a?(a=f().find('option[value$="search-alias='+a+'"]'),b=a.length>0?c(a[0]).text():b):b=f().find("option:selected").text();
return c.trim(b)},getDropdown:d,showDropdown:function(b){r?(typeof b!=="undefined"&&a.flyout.elem().html(b),a.flyout.show()):(typeof b!=="undefined"&&d().hide().html(b),b=n(),d().css({left:b.offset().left,width:b.width()}).show())},hideDropdown:function(){r?a.flyout.hide():d().hide()},getOption:function(a){if(!a)return f().find("option:selected");a=f().find('option[value$="search-alias='+a+'"]');return a.length>0?c(a[0]):c()},getForm:l,getIssPrefixElem:function(){return c("#issprefix")},getSuggestions:function(){return c(".s-suggestion")},
submitForm:function(){l().submit()},getOriginalSearchTerm:function(){return l().data("originalSearchTerm")},getOriginalAlias:function(){return l().data("originalAlias")},isSearchBoxFocused:function(){return i().get(0)===document.activeElement},activateSearchBox:function(){l().addClass("nav-active")},deactivateSearchBox:function(){l().removeClass("nav-active")},getSearchApi:function(){return a}}});h.$Nav.build("sx.iss.TemplateEngine",function(){var c={};return function b(g,e){var j=/^[a-zA-Z0-9_-]+$/.test(g)?
c[g]=c[g]||b(document.getElementById(g).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+g.replace(/[\r\t\n]/g," ").replace(/'(?=[^#]*#>)/g,"\t").split("'").join("\\'").split("\t").join("'").replace(/<#=(.+?)#>/g,"',$1,'").split("<#").join("');").split("#>").join("p.push('")+"');}return p.join('');");return e?j(e):j}});h.$Nav.when("$").build("sx.iss.TemplateInstaller",function(c){function a(a,c){var e=document.createElement("script");e.setAttribute("type",
"text/html");e.setAttribute("id",a);e.text=c;return e}c("body");return{init:function(){var b=document.createDocumentFragment();b.appendChild(a("s-suggestion",'<div id="<#= suggestionId #>"class="s-suggestion"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-isSc="<#= isSpellCorrected #>"data-isFb="<#= isFallback #>"data-type="<#= type #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #><# if (typeof storeHtml === "string") { #> <#= storeHtml #><# } #></div>'));
b.appendChild(a("suggestions-template",'<div id="suggestions-template"><# if (typeof suggestionTitle !== "undefined") { #><div id="suggestion-title"><#= suggestionTitle #></div><# } #><div id="suggestions"><# if (typeof suggestions !== "undefined") {for(var i=0; i < suggestions.length; i++) {var displayString = suggestions[i].display; #><#= displayString #><# }} #></div></div>'));b.appendChild(a("s-separator",'<div id="s-separator"><div class="s-separator"></div></div>'));b.appendChild(a("s-department",
'<div id="<#= suggestionId #>" class="s-suggestion s-highlight-primary"data-alias="<#= alias #>"data-keyword="<#= keyword #>"data-store="<#= store #>"data-type="<#= type #>">Shop the <#= beforePrefix #><span class="s-heavy"><#= prefix #></span><#= suffix #> store</div>'));b.appendChild(a("s-option",'<option value="<#= value #>"><#= store #></option>'));b.appendChild(a("s-minimal",'<div class="s-suggestion s-custom" data-url="<#= url #>"><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));
b.appendChild(a("s-storeText",'<span class="<#= cssClasses #>"><#= store #></span>'));b.appendChild(a("s-corpus",'<div class="s-suggestion" id="<#= suggestionId #>"data-alias="<#= alias #>"data-url="<#= url #>"data-type="<#= type #>"data-keyword="<#= keyword #>"><# if (typeof primeText !== "undefined") { #><span class="s-highlight-primary">[<#= primeText #>] </span><# } #><#= bprefix #><span class="s-heavy"><#= prefix #></span><#= suffix #></div>'));document.body.appendChild(b)}}});h.$Nav.when("sx.iss.DebugUtils",
"sx.iss.DomUtils").build("sx.iss.EventBus.instance",function(c,a){return new function(){function b(a){var b=typeof a,d="";b==="object"&&a.hasOwnProperty("name")?d=a.name:b==="string"&&(d=a);return d}var g={},e={};this.listen=function(e,i,d){var f,l="";if(a.isArray(e)){for(f=0;f<e.length;f++)l=e[f],this.listen(l,i,d),c.logDebug("Listening for: "+l);return this}l=b(e);g[l]||(g[l]=[]);g[l].push({f:i,o:d});c.logDebug("Listening for: "+l);return this};this.trigger=function(a,e){var d=b(a);c.logDebugWithTrace("Trigger: "+
d,e);var d=g[d],f;if(d){for(f=0;f<d.length;f++)d[f].f.call(d[f].o,e);return this}};this.triggerThrottledEvent=function(a,i,d){var f=b(a);c.logDebugWithTrace("Trigger (throttled): "+f,i);var l=g[f],a=e[f];if(l)return d===q&&(d=100),a&&(clearTimeout(a),delete e[f]),a=setTimeout(function(){var a;for(a=0;a<l.length;a++)l[a].f.call(l[a].o,i);delete e[f]},d),e[f]=a,this}}});h.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.PublicApi",function(c,
a,b,g,e,j){function i(a){g.getSearchBox().focus(a)}function d(a){a===q?g.getSearchBox().blur():g.getSearchBox().blur(a)}var f=/node\s*=\s*([\d]+)/,l=/bbn\s*=\s*([\d]+)/,k=/^me=([0-9A-Z]*)/,n=/^\s+/,r=/\s+/g;return{searchAlias:function(){return g.getAliasFromDropdown()},searchNode:function(){var a=g.getAliasDropdown().val().match(f);return a?a[1]:null},bbn:function(){var a=g.getAliasDropdown().val().match(l);return a?a[1]:null},merchant:function(){var a=g.getAliasDropdown().val().match(k);return a?
a[1]:null},encoding:function(){var a=g.getForm().find('input[name^="__mk_"]');if(a.length)return[a.attr("name"),a.val()]},keyword:function(a){return a!==q?g.setKeyword(a):g.getKeyword().replace(n,"").replace(r," ")},submit:function(a){e.logDebugWithTrace("Attaching the submit event handler to the form...");g.getForm().submit(a)},suggest:function(d){a.eventBus.listen(b.globals.suggestionsRendered,function(a){var b=[];c.each(a.suggestions,function(a,d){d.type!=="separator"&&b.push(d)});d(a.searchTerm,
b)})},onFocus:i,onBlur:d,focus:i,blur:d,keydown:function(a){var b="#"+g.getSearchBox().attr("id");g.getForm().delegate(b,"keydown",a)},setupFastLab:function(a){e.logDebugWithTrace("Fastlab",a);j.setFastlabs(a)}}});h.$Nav.when("$","NavDomApi","sx.iss.utils","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.Weblab",function(c,a,b,g,e){return function(a,c){function d(d,c){var i={keywords:c?c.searchTerm:q,alias:b.suggestionUtils.getAliasWithDeepNodeAliasBacked(a.deepNodeISS),fastlabs:e.getTriggeredFastlabs().join("|")};
e.clearTriggeredFastlabs();a.hasOwnProperty(d)&&(a[d](i),g.logDebug("Triggering: "+d+" weblabs"))}b.eventBus.listen(c.keydown,function(a){d("doCTWKeydown",a)});b.eventBus.listen(c.suggestionsRendered,function(a){d("doCTWDisplay",a)})}});h.$Nav.when("sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.IssContext",function(){var c,a,b=[];return{getFastlabs:function(){return a},setFastlabs:function(b){a=b},getTriggeredFastlabs:function(){return b},clearTriggeredFastlabs:function(){b=[]},addTriggeredFastlabs:function(a){b=
b.concat(a)},getConfiguration:function(){return c},setConfiguration:function(a){c=a}}});h.$Nav.when("$","sx.iss.utils","sx.iss.SuggestionTypes","NavDomApi","sx.iss.ReftagBuilder","sx.iss.DebugUtils").build("sx.iss.Reftag",function(c,a,b,g,e,j){return function(b,d,f){function c(a){return(new e).build(a,f.hasOwnProperty("shouldAddImeTag")&&f.shouldAddImeTag())}function k(a){if(a.suggestions===q||a.searchTerm===q)j.logDebug('"suggestions" or "searchTerm" is undefined',a);else{for(var b=e.CONSTANTS.noSearchTermMatchInResults,
d=a.searchTerm,a=a.suggestions,f=0;f<a.length;f++)if(d===a[f].keyword){b=e.CONSTANTS.searchTermMatchInResults;break}p(b)}}function n(){p(e.CONSTANTS.noResults)}function r(a){a.suggestion===q||a.searchTerm===q?j.logDebug('"suggestion" or "searchTerm" is undefined',a):p(c(a))}function p(a){var b=/(ref=[\-\w]+)/,d=/(dd_[a-z]{3,4})(_|$)[\w]*/,f=g.getForm(),c=f.attr("action");b.test(c)?c=d.test(c)?c.replace(d,"$1_"+a):c.replace(b,e.CONSTANTS.reftagBase+a):(c.charAt(c.length-1)!=="/"&&(c+="/"),c+=a);f.attr("action",
c)}d===q&&(d={});f===q&&(f={});a.eventBus.listen(b.selectionChange,r);a.eventBus.listen(b.suggestionsRendered,k);a.eventBus.listen(b.noSuggestions,n);return{create:c,updateReftagAfterRender:k,updateReftagAfterSelection:r,updateReftagAfterNoSuggestions:n,updateFormActionWithReftag:p}}});h.$Nav.when("$","sx.iss.SuggestionTypes","sx.iss.DataAttributes","NavDomApi","sx.iss.DebugUtils").build("sx.iss.ReftagBuilder",function(c,a,b,g,e){function j(){function d(a){a!==q&&n.push(a);return this}function f(a){var a=
g.getOption(a.data("alias")).val(),b=a.indexOf("=");if(b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-"),d=a.substr(0,3);return b?d:d+a.charAt(b+1)}function j(c,l){var m=c.suggestion,h=c.searchTerm,x=c.previousSearchTerm;e.isDebugModeOn()&&e.logDebugWithTrace("Build reftag for search term: "+h+" pre term:"+x,m);var o=k(m),s=o.reftag;d(i.base);l&&d(i.ime);var u;if(m.data(b.fallback.name)===!0)u=i.fallback;else if(m.data(b.spellCorrected.name)===!0)u=i.spellCorrected;u!==q?d(u):(m.data("type")===
a.department.name&&(d(a.a9Xcat.reftag),d(m.data("alias"))),d(s));s!==a.a9.reftag&&s!==a.a9Corpus.reftag?d(0):(o=o.name,o=g.getDropdown().find('.s-suggestion[data-type="'+o+'"]').index(m)+1,d(o));m===q?(d(i.undefinedSugg),m=f(m),d(m)):d(x?x.length:h.length);return n.join(i.separator)}function k(b){var d=a.a9;c.each(a,function(a,f){if(b.data("type")===f.name)return d=f,!1});return d}function f(a){var a=a.val(),b=a.indexOf("=");if(a!==""||b===-1)return"";var a=a.substr(b+1),b=a.indexOf("-")+1,d=a.substr(0,
3);return b?d:d+a.charAt(b)}var n=[];return{build:j,buildFull:function(a,b){return i.reftagBase+j(a,b)}}}var i={base:"ss",fallback:"fb",spellCorrected:"sc",undefinedSugg:"dd",reftagBase:"ref=nb_sb_",noResults:"noss",searchTermMatchInResults:"noss_1",noSearchTermMatchInResults:"noss_2",ime:"ime",separator:"_"};j.CONSTANTS=i;return j});h.$Nav.when("$","NavDomApi","sx.iss.DebugUtils").build("sx.iss.suggestionUtils",function(c,a,b){function g(a,b){return a.toLowerCase().indexOf(b.toLowerCase())}function e(a,
b,d){return{bprefix:a.substr(0,b),prefix:a.substr(b,d),suffix:a.substr(b+d)}}function j(a){return a?a.replace(f,""):q}function i(b){var d;typeof a.getAliasFromDropdown()==="undefined"&&b&&(d=b.searchAliasAccessor(c));return d}var d=/\s/,f=/#(S|E)#/g;return{getPrefixPos:g,getPrefixPosMultiWord:function(a,b){var f=a.toLowerCase().indexOf(b.toLowerCase()),e;if(f===-1)return-1;if(f===0)return 0;e=a[f-1];return e===" "||e==="\t"||e.match(d)?f:-1},splitStringForDisplay:e,markHighlight:function(a,b){var d=
g(b,a);return d>-1?(d=e(b,d,a.length),d.bprefix+"#S#"+d.prefix+"#E#"+d.suffix):b},removeHighlightMark:j,splitHighlightedString:function(a){if(a&&a.length>6){var b=a.indexOf("#S#"),d=a.indexOf("#E#");if(b>-1&&d>-1&&b+3<d)return{bprefix:j(a.substr(0,b)),prefix:j(a.substr(b+3,d-b-3)),suffix:j(a.substr(d+3))}}return q},getAliasWithDeepNodeAliasBacked:function(b){var d=a.getAliasFromDropdown();return d?d:i(b)},getDeepNodeAlias:i,getDeepNodeCategoryName:function(b,d){var f;b&&(f=a.getCategoryNameFromDropdown(b)||
d.searchAliasDisplayNameAccessor());return f},shouldRequestSuggestions:function(d,f){var e;if((d==="department"||d==="a9")&&f.hasOwnProperty("aliases")){var c=a.getAliasFromDropdown()||i(f.deepNodeISS);e=f.aliases==="*"||f.aliases.indexOf(c)>-1;b.logDebug("Should we request suggestions for: alias : "+c+" provider : "+d+"? "+e);return e}return!0}}});h.$Nav.when("sx.iss.TimingProvider.instance","sx.iss.EventBus.instance","sx.iss.suggestionUtils","sx.iss.DependenciesMet").build("sx.iss.utils",function(c,
a,b){return{timingProvider:c,eventBus:a,suggestionUtils:b,now:function(){return(new Date).getTime()},escapeRegExp:function(a){return a.replace(/([.*+?\^${}()|\[\]\/\\])/g,"\\$1")}}});h.$Nav.when("$").build("sx.iss.DomUtils",function(){var c=/\+/g,a=/^\s+/;(function(){if(!Array.prototype.indexOf)Array.prototype.indexOf=function(a,c){var e=this.length>>>0,j=Number(c)||0,j=j<0?Math.ceil(j):Math.floor(j);for(j<0&&(j+=e);j<e;j++)if(j in this&&this[j]===a)return j;return-1}})();return{isHoveredClass:"is-hovered",
getKeyword:function(b){return(b=b.val())?b.replace(a,""):b},isElHoveredOver:function(a){return a.hasClass("is-hovered")},hoverOverEl:function(a){return a.addClass("is-hovered")},hoverOutEl:function(a){return a.removeClass("is-hovered")},isArray:function(a){return Object.prototype.toString.call(a)==="[object Array]"},getFormParams:function(a){for(var a=a.split("?"),g=a.length>1?a[1]:q,g=g?g.split("&"):[],e=g.length,j;e-- >0;)j=g[e].split("="),g[e]={name:j[0],value:j[1].replace(c," ")};return{uri:a[0],
formParams:g}},suggestionClass:".s-suggestion",hiddenInputValue:"frmDynamic",hiddenInputClass:".frmDynamic",areAnySuggestionsHoveredOver:function(a){return a.find(".is-hovered").length>0},getCursorPosition:function(a){a=a.get(0);if("selectionStart"in a)return a.selectionStart;else if(document.selection){a.focus();var c=document.selection.createRange(),e=c.text.length;c.moveStart("character",-a.value.length);return c.text.length-e}return-1}}});h.$Nav.build("sx.iss.DebugUtils",function(){function c(a){if(a&&
a.length>0)for(var a=a.substring(1).split("&"),b=0;b<a.length;b++){var d=a[b].split("=");if(d[0]==="debug"){for(var f in e)e.hasOwnProperty(f)&&(e[f]=d[1].indexOf(f)!==-1?!0:!1);break}}}function a(){return e.iss||e.isstrace}function b(){return e.isstrace}function g(b,e){a()&&h.console&&(e!==q?console.debug(b,e):console.debug(b))}var e={iss:!1,isstrace:!1,noiss:!1,isspolyfill:!1,isscf:!1};c(h.location.search);return{init:c,logDebug:g,logDebugWithTrace:function(a,e){g(a,e);b()&&console.trace()},isDebugModeOn:a,
isDebugModeOnWithTrace:b,isDisableISS:function(){return e.noiss},isUsingPolyFill:function(){return e.isspolyfill},isQIAEnabled:function(){return e.isscf}}});h.$Nav.build("sx.iss.ObjectUtils",function(){return{freeze:function(c){Object.freeze&&c&&Object.freeze(c)}}});h.$Nav.when("$","sx.iss.DebugUtils").run(function(c,a){a.isDisableISS()||((!c.fn.delegate||a.isUsingPolyFill())&&c.extend(c.fn,{delegate:function(b,g,e){return this.bind(g,function(g){var i=c(g.target);if(i.is(b)||i.parents(b).length>
0)return a.logDebug("delegate ",{selector:b,target:i,event:g}),e.apply(i,arguments)})}}),h.$Nav.declare("sx.iss.DependenciesMet"))});h.$Nav.when("sx.iss.DepartmentDataFormatter").build("sx.iss.DepartmentData",function(c){var a=[["instant-video","Amazon Video",["Amazon","Instant","Video","movies","rentals"]],["appliances","Appliances",["Appliances"]],["mobile-apps","Apps for Android",["Apps","Android","mobile"]],["arts-crafts","Arts, Crafts & Sewing",["arts","crafts","sewing"]],["automotive","Automotive",
["automotive","cars"]],["baby-products","Baby Products",["baby","products"]],["beauty","Beauty",["beauty","makeup","hair"]],["stripbooks","Books",["books","textbooks","rentals"]],["mobile","Cell Phones & Accessories","cell,phones,mobile,cases,iphone,galaxy,nexus".split(",")],["collectibles","Collectibles & Fine Art",["collectibles","fine","art"]],["computers","Computers",["computers","pc","laptop","desktop"]],["electronics","Electronics",["electronics"]],["financial","Credit Cards",["credit","cards"]],
["gift-cards","Gift Cards Store",["gift","cards"]],["grocery","Grocery & Gourmet Food",["grocery","gourmet","food"]],["hpc","Health & Personal Care",["health","personal","care"]],["garden","Home & Kitchen",["home","kitchen","furniture","art"]],["industrial","Industrial & Scientific",["Industrial","Scientific"]],["digital-text","Kindle Store",["kindle","store","ebooks"]],["magazines","Magazine Subscriptions",["magazines","subscriptions"]],["movies-tv","Movies & TV","movies,tv,dvds,vhs,video,blu ray,bluray,blu-ray".split(",")],
["digital-music","MP3 Music",["mp3","music"]],["popular","Music",["music","cds","autorip","vinyl"]],["mi","Musical Instruments",["musical","instruments","guitars","dj"]],["office-products","Office Products",["office","products","school","toner"]],["lawngarden","Patio, Lawn & Garden",["patio","lawn","garden"]],["pets","Pet Supplies","pet,supplies,dogs,cats,birds,fish".split(",")],["software","Software",["software"]],["sporting","Sporting & Outdoors",["sporting","outdoors","sports"]],["tools","Tools & Home Improvement",
["tools","home","improvement"]],["toys-and-games","Toys & Games",["toys","games"]],["videogames","Video Games","video,games,xbox,ps3,ps4,wii,playstation".split(",")],["wine","Wine",["wine"]],["pantry","Prime Pantry",["prime","pantry"]]],b=[["fashion","Clothing, Shoes & Jewelry","clothing,clothes,luggage,hats,shirts,jacket,wallets,sunglasses,jewelry,shoes,handbags,sandals,boots,watches".split(",")],["fashion-mens","Men's Clothing, Shoes & Jewelry","mens,clothing,clothes,shoes,jewelry,mens clothing,mens shoes,mens jewelry,watches,mens watches".split(",")],
["fashion-womens","Women's Clothing, Shoes & Jewelry","womens,clothing,clothes,shoes,jewelry,womens clothing,womens shoes,womens jewelry,watches,womens watches".split(",")],["fashion-baby","Baby Clothing, Shoes & Jewelry","baby,clothing,clothes,shoes,jewelry,baby clothing,baby shoes,baby jewelry".split(",")],["fashion-boys","Boys Clothing, Shoes & Jewelry","boys,clothing,clothes,shoes,jewelry,boys clothing,boys shoes,boys jewelry".split(",")],["fashion-girls","Girls' Clothing, Shoes & Jewelry","girls,clothing,clothes,shoes,jewelry,girls clothing,girls shoes,girls jewelry".split(",")]],
g=[["jewelry","Jewelry",["jewelry"]],["shoes","Shoes",["shoes","handbags","sandals","boots"]],["apparel","Clothing & Accessories","clothing,clothes,hats,shirts,jacket,wallets,sunglasses".split(",")]];return{getData:function(e){var j=a,e=typeof e!=="undefined"&&e.hasOwnProperty("isWayfindingEnabled")&&e.isWayfindingEnabled===1?b:g,j=j.concat(e);return c.format(j)}}});h.$Nav.build("sx.iss.DepartmentDataFormatter",function(){return{format:function(c){for(var a=[],b=0;b<c.length;b++){var g=c[b];a.push({id:g[0],
alias:g[0],keyword:"",type:"department",store:g[1],name:"",triggerWords:g[2],sn:!1})}return a}}});h.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.SuggestionTypes",function(c){var a={a9:{name:"a9",reftag:"i",templateId:"s-suggestion"},a9Xcat:{name:"a9-xcat",reftag:"c",templateId:"s-suggestion"},a9XOnly:{name:"a9-xcat-only",reftag:"xo",source:"xo",templateId:"s-suggestion"},a9Corpus:{name:"a9-corpus",reftag:"cp",reftagTemplate:"REF_TAG",templateId:"s-corpus"},department:{name:"department",reftag:"deptiss",
templateId:"s-department"}};c.freeze(a);return a});h.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.InfoTypes",function(c){var a={actor:"actor",author:"author",director:"director",seasonTitle:"season_title",title:"title"};c.freeze(a);return a});h.$Nav.build("sx.iss.DataAttributes",function(){return{fallback:{name:"isfb"},spellCorrected:{name:"issc"}}});h.$Nav.build("sx.iss.TimingEvents",function(){return{latency:{group:"Latency",events:{timeToDisplay:"timeToDisplay"}}}});h.$Nav.when("sx.iss.DebugUtils").build("sx.iss.Events",
o);h.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.Platform",function(c){var a={name:"desktop",cid:"amazon-search-ui",callback:"String",needExtraParams:!0};c.freeze(a);return a});h.$Nav.when("$").build("sx.iss.TimingProvider.instance",function(c){return new function(){var a={};this.startTimer=function(b,c){a[b]||(a[b]={});a[b][c]={start:+new Date}};this.stopTimer=function(b,c){var e=a[b]&&a[b][c];if(!e)return-1;e.end=+new Date;return e.end-e.start};this.getTimings=function(b){return a[b]};this.getTimingStats=
function(b){var g={name:b},e=0,j=0,i=q,d=q,f=0,l=0,k=[],n=0,r=0;if(!a[b])return q;c.each(a[b],function(a,b){if(b.start&&b.end){l=b.end-b.start;k.push(l);f++;j+=l;if(!i||l<i)i=l;if(!d||l>d)d=l}});k.sort();g.n=f;g.avg=j/f;g.min=i;g.max=d;g.med=f===1?k[0]:f%2?(k[Math.floor(f/2)]+k[Math.ceil(f/2)])/2:k[f/2];for(e=0;e<f;e++)n=k[e]-g.avg,n*=n,r+=n;g.stddev=Math.sqrt(r/f);return g};this.getTimingWithDisplayLatency=function(b,c){var e=a[b]&&a[b][c];return!e?-1:e.end-e.start+100}}});h.$Nav.when("$","sx.iss.utils",
"NavDomApi","sx.iss.Events","sx.iss.SuggestionTypes","sx.iss.A9SuggestionQueryConstructors","sx.iss.A9SuggestionResultsProcessors","sx.iss.DebugUtils").build("sx.iss.A9SuggestionProvider",function(c,a,b,g,e,j,i,d){var f="a9",l=e.a9;return function(b,n,r){function p(b,j){var i=++h,l,p;x=document.getElementsByTagName("head").item(0);o="JscriptId"+i;s=document.createElement("script");s.setAttribute("type","text/javascript");s.setAttribute("charset","utf-8");s.setAttribute("src",j);s.setAttribute("id",
o);s.onload=s.onreadystatechange=function(){if(!(l||this.readyState!==q&&this.readyState!=="loaded"&&this.readyState!=="complete")){l=!0;if(completion!=="undefined"){var j=m(),k=!j||c.inArray(j,I)===-1?e.a9:e.a9Corpus;p=t.getResultsProcessor(k.name).processResults(b,j,completion)}this.onload=this.onreadystatechange=null;try{x.removeChild(s)}catch(n){d.logDebug(n)}a.timingProvider.stopTimer(f,i);j={searchTerm:b,suggestionSets:p};k=g.createEvent(f,r.suggestionsReady);a.eventBus.trigger(k,j)}};a.timingProvider.startTimer(f,
i);x.appendChild(s)}function m(){var k;var b="aps",b=[],b=n.aliases;return k=(b=n.implicitAlias?[n.implicitAlias]:typeof b==="string"?b.split(","):b)&&b.length===1?b[0]:a.suggestionUtils.getAliasWithDeepNodeAliasBacked(n.deepNodeISS),b=k}var h=0,x,o,s,u=new j(n),t=new i(n),I=n.issCorpus||[];a.eventBus.listen(r.a9SuggestionsNeeded,function(b){if(a.suggestionUtils.shouldRequestSuggestions(f,n))if(!b||!b.length){var b={searchTerm:b,suggestions:[]},d=g.createEvent(f,r.suggestionsReady);a.eventBus.trigger(d,
b)}else{var d=m(),j=!d||c.inArray(d,I)===-1?e.a9:e.a9Corpus;(d=u.getUrlConstructor(j.name).constructUrl(b,d))&&p.call(this,b,d)}},this);return{getName:function(){return f},processResults:t.getResultsProcessor(l.name).processResults}}});h.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.Platform","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.A9SuggestionQueryConstructors",function(c,a,b,g,e,j,i,d){return function(f){function l(a){return{constructUrl:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+
a+" when asking for query constructors");return""}}}function k(a){var d=g.getCursorPosition(b.getSearchBox());return d>-1?{q:encodeURIComponent(a.substring(0,d).replace(/^\s+/,"").replace(/\s+/g," ")),qs:encodeURIComponent(a.substring(d))}:{q:encodeURIComponent(a)}}function n(a){var b="?";c.each(a,function(a,d){b+=a+"="+d+"&"});return b}function r(b){var d={xcat:f.xcat,cf:f.cf,noCacheIE:a.now()};if(f.fb!==q)d.fb=f.fb;if(f.np!==q)d.np=f.np;if(f.issPrimeEligible&&c.inArray(b,f.issPrimeEligible)!==-1)d.pf=
1,d.fb=0;d.sc=1;return d}var p=f.protocol||h.parent.document.location.protocol||"http:";p==="file:"&&(p="http:");var m={};m[e.a9.name]=new function(){var a=p+"//"+f.src,b={method:"completion",mkt:f.mkt,client:j.cid,x:j.callback};return{constructUrl:function(f,e){var g=c.extend({},b,{"search-alias":e},k(f));j.needExtraParams&&c.extend(g,r(e));d.getFastlabs()&&c.extend(g,{w:d.getFastlabs()});return a+n(g)}}};m[e.a9Corpus.name]=new function(){var a=p+"//"+f.src.replace("/search","/v2.0"),b={"num-corpus":10,
"num-query":5,client:j.cid,m:f.obfMkt,fb:1,xcat:1,method:"completion",cf:0,sc:1,conf:1,x:j.callback};return{constructUrl:function(d,f){var e=c.extend({},b,{"search-alias":f},k(d));return a+n(e)}}};return{getUrlConstructor:function(a){return m.hasOwnProperty(a)?m[a]:new l(a)}}}});h.$Nav.when("$","sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.SuggestionTypes","sx.iss.InfoTypes","sx.iss.DebugUtils","sx.iss.IssContext").build("sx.iss.A9SuggestionResultsProcessors",function(c,a,b,g,e,j,i,d){var f;
f="aps";return function(c){function k(a){return{processResults:function(){i.logDebugWithTrace("Invalid suggestion type provided: "+a+" when asking for result processing");return""}}}function n(b,d,f,e,c,g,j){var i=a.suggestionUtils.getPrefixPos(e,f),l;c||i===-1?(f=e,i=l=""):(l=a.suggestionUtils.splitStringForDisplay(e,i,f.length),f=l.bprefix,i=l.prefix,l=l.suffix);return{type:g,isSpellCorrected:c,bprefix:f,prefix:i,suffix:l,keyword:e,isFirst:j===0,alias:b,store:d,isDeepNode:b!==q&&d!==q}}function r(a,
b,d,f){a.store=b.name;a.alias=b.alias;a.type=d?e.a9XOnly.name:e.a9Xcat.name;a.isFallback=f;return a}function p(a,d,c){d.isFirst=!1;if(c)d.type=e.a9XOnly.name;else if(d.type=e.a9Xcat.name,c=b.getAliasFromDropdown(),c!==f)d.store=b.getCategoryNameFromDropdown(c),d.alias=c,a.push(m(d));d.store=b.getCategoryNameFromDropdown(f);d.alias=f;a.push(m(d))}function m(a,d){var f={type:a.type,bprefix:a.bprefix,prefix:a.prefix,suffix:a.suffix,keyword:a.keyword,alias:a.alias||d,isSpellCorrected:a.isSpellCorrected,
isFallback:a.isFallback,isDeepNode:a.isDeepNode},g;if(f.type===e.a9Xcat.name||f.type===e.a9XOnly.name||f.isDeepNode===!0){if(a.isFirst||!c.noXcats)a.store?g=a.store:a.isFirst&&(g=b.getCategoryNameFromDropdown())}else g=q;f.store=g;g=f.alias;var j="/s?k="+encodeURIComponent(a.keyword);typeof g!==q&&(j+="&i="+encodeURIComponent(g));f.url=j;return f}var h={};h[e.a9.name]=new function(){var b=e.a9.name;return{processResults:function(f,j,i){var k=i[1],h=i[2]||[],i=i[3]||[],o=0,v=[],q=[],L,D,E;E=!1;for(var H=
0;H<h.length;H++){var z=h[H];if(z.hasOwnProperty("source"))for(var z=z.source,C=0;C<z.length;C++)if(z[C]==="fb"){E=!0;break}}H=!1;for(z=0;z<h.length;z++)if(C=h[z],C.hasOwnProperty("nodes")&&C.nodes.length>0){H=!0;break}if(z=c.hasOwnProperty("cf"))if(z=c.cf){z=!1;for(C=0;C<h.length;C++){var A=h[C];if(A.hasOwnProperty("nodes")&&A.nodes.length>0&&A.hasOwnProperty("source")&&g.isArray(A.source)&&A.source[0]==="xo"){z=!0;break}}}c.deepNodeISS&&(L=a.suggestionUtils.getDeepNodeAlias(c.deepNodeISS),D=a.suggestionUtils.getDeepNodeCategoryName(L,
c.deepNodeISS));C=typeof L!=="undefined";for(A=0;A<k.length;A++){var K=n(L,D,f,k[A],h&&h[A]&&h[A].sc==="1",b,A);E||v.push(m(K,j));if(!c.noXcats&&H){!E&&A===0&&(C||p(q,K,z),(z||!C)&&v.shift());for(var y=h[A],P=y&&y.source&&y.source[0]==="fb",y=y.nodes||[],F=0;F<y.length&&o<4;F++)K=r(K,y[F],z,P),q.push(m(K,j)),o++}}f={};f[e.a9.name]=v;f[z?e.a9XOnly.name:e.a9Xcat.name]=q;i.length>0&&i[0].hasOwnProperty("t")&&d.addTriggeredFastlabs(i[0].t);return f}}};h[e.a9Corpus.name]=new function(){function b(d,f,
g,j,i,p,k){f=n(f,q,g,j,i,e.a9Corpus.name,k);if(g=a.suggestionUtils.splitHighlightedString(j))f.bprefix=g.bprefix,f.prefix=g.prefix,f.suffix=g.suffix;j=a.suggestionUtils.removeHighlightMark(j);f.keyword=j;f.text=j;f.url="/dp/"+d+"/"+e.a9Corpus.reftagTemplate+"?ie=utf8&keywords="+encodeURIComponent(j);if(p)f.primeText=c.primeText;return f}function d(a){for(var b=[],f=0;f<a.length;f++)b.push(a[f].field);return b}return{processResults:function(f,g,i){var k=[],h=[],i=i.suggs,o,v;if(i.length===0)return[];
for(var L=i.length,D=0;D<i.length;D++)if(i[D].hasOwnProperty("corpus")){var q=d(i[D].source);if((q.indexOf(j.title)>=0||q.indexOf(j.seasonTitle)>=0)&&i[D].corpus.length>1)i[D].alwaysShowDirector=!0}else{L=D;break}c.deepNodeISS&&(o=a.suggestionUtils.getDeepNodeAlias(c.deepNodeISS),v=a.suggestionUtils.getDeepNodeCategoryName(o,c.deepNodeISS));for(D=L;D<i.length&&h.length<4;D++){var H=i[D];if(q=H.xcats)for(var z=q.hasOwnProperty("sc")&&q.sc!==0,C=H.hasOwnProperty("fb")&&H.fb!==0,A=0;A<q.length&&h.length<
4;A++){var y=h,J=o,P=q[A],F=C,O=D-L+A,G=n(J,v,f,H.sugg,z,e.a9Xcat.name,O),G=r(G,P,!1,F);O===0&&!F&&typeof J==="undefined"?p(y,G):y.push(m(G))}}o=10-h.length;for(D=0;D<L&&k.length<o;D++){H=i[D];v=H.corpus;q=d(H.source);for(A=0;A<v.length&&k.length<10;A++){z=v[A];C=H;y=z.asin_info;J=q;P=f;F="";for(O=0;O<y.length;O++){var M=y[O],G=M.type,M=M.value;if(G===j.title||G===j.seasonTitle)F+=a.suggestionUtils.markHighlight(P,M[0]);C.alwaysShowDirector&&G===j.director?F+=c.directedByText.replace("{director}",
M[0]):J.indexOf(G)>=0&&M.indexOf(C.sugg)>=0&&(M=a.suggestionUtils.markHighlight(P,C.sugg),G===j.actor?F+=c.starringText.replace("{actor}",M):G===j.director&&(F+=c.directedByText.replace("{director}",M)))}C=F;y=z.hasOwnProperty("is_prime")&&z.is_prime===1;k.push(b(z.asin,g,f,C,!1,y,A))}}f={};f[e.a9Corpus.name]=k;f[e.a9Xcat.name]=h;return f}}};return{getResultsProcessor:function(a){return h.hasOwnProperty(a)?h[a]:new k(a)}}}});h.$Nav.when("$","sx.iss.utils","sx.iss.DepartmentData","NavDomApi","sx.iss.Events").build("sx.iss.DepartmentSuggestionProvider",
function(c,a,b,g,e){function j(j,k){function n(n){if(a.suggestionUtils.shouldRequestSuggestions(i,j)){var p={searchTerm:n,suggestionSets:{}},m=[],o=RegExp("\\b"+a.escapeRegExp(n)+"(.*)","i");if(n.length>=d&&g.getKeyword().length===n.length){var x,w,s,u;c.each(b.getData(j),function(b,d){u=s=w="";if(o.test(d.triggerWords)||o.test(d.store)){d.position=m.length===0?0:m.length+1;var e=a.suggestionUtils.getPrefixPos(d.store,n);e===-1?u=d.store:(x=a.suggestionUtils.splitStringForDisplay(d.store,e,n.length),
w=x.bprefix,s=x.prefix,u=x.suffix);d.beforePrefix=w;d.prefix=s;d.suffix=u;m.push(d);if((e=h.ue)&&e.count){var c=i+d.alias.replace("-","");e.count(c,e.count(c)+1)}}if(m.length===f)return!1})}p.suggestionSets[i]=m;var t=e.createEvent(i,k.suggestionsReady);a.eventBus.trigger(t,p)}}(function(){var b=e.createEvent(i,k.suggestionsNeeded);a.eventBus.listen(b,n)})()}var i="department",d=3,f=3;j.prototype.getName=function(){return i};return j});h.$Nav.when("sx.iss.utils").build("sx.iss.HelpSuggestionProvider",
function(c){var a=[{type:"help",pat:/^return/i,text:"Looking for help with returns? Try this.",url:""},{type:"help",pat:/^track/i,text:"Looking for help with tracking? Try this.",url:""},{type:"help",pat:/^gift[\s*]w/i,text:"Looking for help with gift wrapping? Try this.",url:""},{type:"help",pat:/^canc/i,text:"Looking for help with order cancellation? Try this.",url:""},{type:"help",pat:/^refu[\s*]/i,text:"Looking for help with refund? Try this.",url:""},{type:"help",pat:/^passw[\s*]/i,text:"Looking for help with passwords? Try this.",
url:""},{type:"help",pat:/^log(ging\s*)?o/i,text:"Looking for help with logging out? Try this.",url:""}];return function(){this.getName=function(){return"help"};c.eventBus.listen("help-suggestionsNeeded",function(b){var g,e=[];for(g=0;g<a.length;g++)b.match(a[g].pat)&&e.push(a[g]);c.eventBus.trigger("help-suggestionsReady",{searchTerm:b,suggestions:e})},this)}});h.$Nav.when("$","sx.iss.utils").build("sx.iss.RecentSearchSuggestionProvider",function(c,a){return function(b){var g=/[^\w]/;this.getName=
function(){return"recent"};var e=o.createEvent("recent",b.suggestionsNeeded);a.eventBus.listen(e,function(e){var i=[];if(h.sx&&h.sx.searchsuggest&&h.sx.searchsuggest.searchedText){var d=h.sx.searchsuggest.searchedText,f={},l,k,n,r,p,m,v=!e||!g.test(e)?e:c("<div></div>").text(e).html();for(r=0;r<d.length;r++)if(k=d[r].keywords,l=!k||!g.test(k)?k:c("<div></div>").html(k).text(),n=a.suggestionUtils.getPrefixPosMultiWord(k,v),!f[k]&&a.suggestionUtils.getPrefixPosMultiWord(l,e)!==-1)n===-1?(n=k,m=p=""):
(p=a.suggestionUtils.splitStringForDisplay(k,n,v.length),n=p.bprefix,m=p.prefix,p=p.suffix),i.push({type:"recent",spellCor:!1,bprefix:n,prefix:m,suffix:p,keyword:l,originalKeywords:k,deleteUrl:d[r].deleteUrl}),f[k]=1}d=o.createEvent("recent",b.suggestionsReady);a.eventBus.trigger(d,{searchTerm:e,suggestions:i})},this)}});h.$Nav.when("$","sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.SuggestionDisplayProvider",function(c,a,b){return function(a,e,j){var i,d;this.getDisplay=function(a){if(!i(a))return q;
c.extend(a,j);return d(a)};i=typeof a==="string"?function(b){return b.type===a}:a;d=b(e)}});h.$Nav.when("$","sx.iss.utils").build("sx.iss.SuggestionHighlightingProvider",function(c,a){return function(b){function g(a){a=a.currentTarget.id;f&&f.removeClass(f.attr("data-selected-class"));f=c("#"+a);d=parseInt(a.substr(6));f.addClass(f.attr("data-selected-class"))}function e(a){a=a.currentTarget.id;f&&f.attr("id")===a&&(f.removeClass(f.attr("data-selected-class")),f=q,d=-1)}var j=this,i,d=-1,f;a.eventBus.listen(b.suggestionsDisplayed,
function(a){var b;i=a;d=-1;f=q;for(a=0;a<i.suggestions.length;a++)b=c("#"+i.suggestions[a].suggestionId),b.bind("mouseover",j,g).bind("mouseout",j,e)},this).listen(b.upArrowPressed,function(){i&&(f&&f.removeClass(f.attr("data-selected-class")),d--,d===-1?a.eventBus.trigger(b.suggestionSelected,{keyword:i.searchTerm}):(d===-2&&(d=i.suggestions.length-1),f=c("#issDiv"+d),f.addClass(f.attr("data-selected-class")),a.eventBus.trigger(b.suggestionSelected,i.suggestions[d])))},this).listen(b.downArrowPressed,
function(){i&&(f&&f.removeClass(f.attr("data-selected-class")),d++,d===i.suggestions.length?(d=-1,a.eventBus.trigger(b.suggestionSelected,{keyword:i.searchTerm})):(f=c("#issDiv"+d),f.addClass(f.attr("data-selected-class")),a.eventBus.trigger(b.suggestionSelected,i.suggestions[d])))},this)}});h.$Nav.when("sx.iss.utils","sx.iss.SuggestionTypes","sx.iss.TemplateEngine").build("sx.iss.IssDisplayProvider",function(c,a,b){return function(g,e,j,i,d){function f(a){c.eventBus.trigger(i.suggestionsNeeded,a)}
function l(b){var f=e.sequence(b),b=b.searchTerm,g=h++;c.timingProvider.startTimer("IssDisplayProvider",g);if(f.length===0)c.eventBus.trigger(i.noSuggestions,b);else{for(var l=j,o=0,s=0;s<f.length;s++){var u=f[s];if(u.type!=="separator")u.suggestionId="issDiv"+o,o++;var t=u,I="";I+=u.isDeepNode===!0?"s-highlight-secondary":"s-highlight-primary";t.cssClasses=I;for(var B,t=0;t<l.length;t++)if(B=l[t],B=k(B,u),B=B.getDisplay(u))break;u.display=B}l=f&&f.length>0&&f[0].type===a.a9Corpus.name&&d.hasOwnProperty("issCorpusSugText");
l=n({suggestions:f,suggestionTitle:l?d.issCorpusSugText:d.hasOwnProperty("sugText")?d.sugText:""});c.timingProvider.stopTimer("IssDisplayProvider",g);c.eventBus.trigger(i.suggestionsReadyForDisplay,{searchTerm:b,display:l,suggestions:f})}}function k(a,b){var d=a;if(a.hasOwnProperty("provider")&&a.hasOwnProperty("partials")){for(d=0;d<a.partials.length;d++){var f=a.partials[d],e=f.provider.getDisplay(b);f.hasOwnProperty("formatter")&&(e=f.formatter.string.replace(f.formatter.toReplace,e));b[f.key]=
e}d=a.provider}return d}var n=b(g),h=0;(function(){c.eventBus.listen(i.suggestionsReady,l,this);c.eventBus.listen(["parentFocused","searchTermChanged"],f,this)})();return{processPartials:k}}});h.$Nav.when("sx.iss.utils","sx.iss.Events").build("sx.iss.ArraySuggestionProvider",function(c,a){return function(b,g){function e(b){for(var e=[],h=b.toLowerCase(),p=0;p<i.length;p++){var m=i[p];if(m.toLowerCase().indexOf(h)!==-1&&e.length<f){var m={term:m,searchTerm:b,url:d[p]},o=c.suggestionUtils.getPrefixPos(m.term,
m.searchTerm),o=c.suggestionUtils.splitStringForDisplay(m.term,o,m.searchTerm.length),m={type:l,bprefix:o.bprefix,prefix:o.prefix,suffix:o.suffix,keyword:m.searchTerm,url:m.url,isExactMatch:m.term===m.searchTerm};e.push(m)}}b={searchTerm:b,suggestionSets:{array:e}};e=a.createEvent(j,g.suggestionsReady);c.eventBus.trigger(e,b)}var j="array",i=b[0],d=b[1],f=10,l="array";(function(){var b=a.createEvent(j,g.suggestionsNeeded);c.eventBus.listen(b,e,this)})();return{name:j}}});h.$Nav.when("$","sx.iss.utils",
"sx.iss.TimingEvents","sx.iss.TemplateEngine","NavDomApi","sx.iss.SuggestionTypes","sx.iss.ReftagBuilder").build("sx.iss.DesktopSearchBoxEventHandler",function(c,a,b,g,e,j,i){var d=e.getSearchApi();return function(f){function l(){o=!0;w||(w=!0)}function k(){x=!0}function n(){e.activateSearchBox()}function r(){e.deactivateSearchBox()}a.eventBus.listen(f.selectionChange,function(d){p===q&&(p=e.getAliasFromDropdown());if(d.isScrollIntoSearchBox===!0)d=d.previousSearchTerm,e.getIssPrefixElem().remove(),
m.val(d),e.getAliasDropdown().val("search-alias="+p).trigger("change");else{var f=a.timingProvider.getTimingWithDisplayLatency(b.latency.group,b.latency.events.timeToDisplay),f=e.getKeyword()+","+e.getOriginalAlias()+","+f,j=e.getIssPrefixElem();j.length>0?j.attr("value",f):(f=c('<input type="hidden"/>').attr("id","issprefix").attr("name","sprefix").attr("value",f),e.getForm().append(f));var d=d.suggestion,i=d.attr("data-alias"),j=e.getOption(i),f=e.getAliasDropdown(),i="search-alias="+i;j.length===
0?(j=d.data("store"),j!==q&&j!==""&&f.append(g("s-option",{value:i,store:j}))):i=j.val();f.val(i).trigger("change");e.setKeyword(d.attr("data-keyword"))}});a.eventBus.listen(f.hideDropdown,function(b){o===!0&&x===!0&&(b.keyCode===27||b.keyCode===13)?(o=x=!1,a.eventBus.triggerThrottledEvent(f.suggestionsNeeded,e.getKeyword())):(e.hideDropdown(),e.getIssPrefixElem().remove(),p=q)});a.eventBus.listen(f.suggestionClicked,function(b){var d=b.suggestion;a.eventBus.trigger(f.updateSearchBox,d);b={suggestion:d,
searchTerm:e.getKeyword(),previousSearchTerm:b.previousSearchTerm};a.eventBus.trigger(f.selectionChange,b);e.hideDropdown();d.attr("data-type")===j.a9Corpus.name?(d=d.attr("data-url"),h.location=d.replace(j.a9Corpus.reftagTemplate,(new i).buildFull(b,w))):e.submitForm()});a.eventBus.listen(f.noSuggestions,function(){e.hideDropdown()});a.eventBus.listen(f.suggestionsNeeded,function(){p=e.getAliasFromDropdown()});d===q&&(a.eventBus.listen(f.searchBoxFocusIn,n),a.eventBus.listen(f.searchBoxFocusOut,
r));d!==q?(d.on("compositionstart",l),d.on("compositionend",k)):c("#navbar").delegate("#twotabsearchtextbox","compositionstart",l).delegate("#twotabsearchtextbox","compositionend",k);var p,m=e.getSearchBox(),o=!1,x=!1,w=!1;return{getWasCompositionUsed:function(){return w}}}});h.$Nav.when("sx.iss.utils").build("sx.iss.A9SearchSuggestionEventHandler",function(c){return function(a){var b;this.getDelegateReqs=function(){return{selectors:".a9_suggestion,.suggestion_with_query_builder",events:"click"}};
this.handleEvent=function(g){var e=g.target||g.srcElement,g=parseInt(g.currentTarget.id.substr(6),10);e.className&&e.className.indexOf("suggest_builder")!=-1?c.eventBus.trigger(a.updateSearchTerm,b.suggestions[g].keyword):c.eventBus.trigger(a.suggestionClicked,{suggestion:b.suggestions[g]})};c.eventBus.listen(a.suggestionsDisplayed,function(a){b=a},this)}});h.$Nav.when("sx.iss.utils").build("sx.iss.RecentSearchSuggestionEventHandler",function(c){return function(a){function b(b){var e,d,f,g;e=location.protocol+
"//"+location.host+b.deleteUrl;d=h.sx.searchsuggest.searchedText;for(f=0;f<d.length;f++)if(d[f].keywords===b.originalKeywords){g=f;break}g!==-1&&d.splice(g,1);c.eventBus.trigger(a.focusOnParent);var k;h.XMLHttpRequest?k=new XMLHttpRequest:h.ActiveXObject&&(k=new ActiveXObject("Microsoft.XMLHTTP"));if(k&&e)try{k.open("GET",e,!0),k.send(null)}catch(n){}}var g=this,e;this.getDelegateReqs=function(){return{selectors:".recent_search_suggestion",events:"click"}};this.handleEvent=function(j){var i=j.target||
j.srcElement,j=parseInt(j.currentTarget.id.substr(6),10);i.className&&i.className.indexOf("iss_sh_delete")!=-1?b.call(g,e.suggestions[j]):c.eventBus.trigger(a.suggestionClicked,{suggestion:e.suggestions[j]})};c.eventBus.listen(a.suggestionsDisplayed,function(a){e=a},this)}});h.$Nav.when("$","sx.iss.utils","sx.iss.DomUtils","sx.iss.TimingEvents","sx.iss.TemplateEngine","sx.iss.DebugUtils").build("sx.iss.SearchBoxEventHandler",function(c,a,b,g,e,j){var i=[37,38,39,40,91,92,93,192];return function(d,
f,e){function g(d){a.eventBus.trigger(e.keydown);var f=d.keyCode,i=f===40,p=f===38,k;if(w.find("#suggestions-template").is(":visible")){if(i||p){u===q&&(u=b.getKeyword(s));var m=w.find(".s-suggestion"),n=m.index(c(".s-selected"));(p=n===0&&p||n+1===m.length&&i)?w.find(".s-suggestion").removeClass("s-selected"):(j.logDebug("highlighting suggestion"),k=w.find(".s-suggestion"),m=k.index(o()),n=k.length,i?(i=-1,m===-1||m===n-1?i=0:m<n&&(i=m+1)):(i=-1,m<1?i=n-1:m<=n&&(i=m-1)),k.eq(m).removeClass("s-selected"),
i=k.eq(i),i.addClass("s-selected"),k=i);a.eventBus.trigger(e.selectionChange,{suggestion:k,isScrollIntoSearchBox:p,searchTerm:u,previousSearchTerm:t});s.val()!==""&&d.preventDefault()}f===13&&(f=o(),f.length>0&&(a.eventBus.trigger(e.suggestionClicked,{suggestion:f,searchTerm:u,previousSearchTerm:t}),d.preventDefault()))}}function n(d){d=d.keyCode;d===13?m(d):d===27?m(d):(u=b.getKeyword(s),u!==t&&i.indexOf(d)===-1&&(u===q||u===""?(m(),t=""):(a.eventBus.triggerThrottledEvent(e.suggestionsNeeded,u),
t=u)))}function h(){setTimeout(function(){return function(){m();a.eventBus.trigger(e.searchBoxFocusOut)}}(),300)}function p(){a.eventBus.trigger(e.searchBoxFocusIn)}function m(b){u=q;a.eventBus.trigger(e.hideDropdown,{keyCode:b})}function o(){return w.find(".s-suggestion.s-selected")}var x,w,s,u,t;(function(){if(f!==q){x=f.$form;w=f.$dropdown;s=f.$searchbox;var a="#"+s.attr("id");x.delegate(a,"focusin",p).delegate(a,"focusout",h).delegate(a,"keydown",g).delegate(a,"keyup",n);t=s.val()}})()}});h.$Nav.when("$",
"sx.iss.utils","NavDomApi","sx.iss.DomUtils","sx.iss.DebugUtils").build("sx.iss.SuggestionEventHandler",function(c,a,b,g,e){return function(b,i){i.delegate(".s-suggestion","click",function(d){var f=c(this);e.logDebug("Suggestion clicked",f);a.eventBus.trigger(b.suggestionClicked,{suggestion:f});d.preventDefault()}).delegate(".s-suggestion","mouseover",function(a){g.hoverOverEl(c(a.currentTarget))}).delegate(".s-suggestion","mouseout",function(a){g.hoverOutEl(c(a.currentTarget))})}});h.$Nav.when("$",
"sx.iss.utils","sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.CustomSearchBoxEventHandler",function(c,a,b,g){return function(e,j,i){function d(a){k.hide();typeof i.manualOverride==="function"&&(a=i.manualOverride(a),a!==null&&a.length>0&&f(a));c(i.submitId).removeAttr("disabled")}function f(a){l.find(g.hiddenInputClass).remove();a=g.getFormParams(a);b.logDebug("Updating form with params.",a);l.attr("action",a.uri);for(var d="",a=a.formParams,f=0;f<a.length;f++){var e=a[f],c=decodeURIComponent(e.value);
d+='<input type="hidden" class="'+g.hiddenInputValue+'" name="'+e.name+'" value="'+c+'"/>'}l.append(d)}var l,k;l=e.$form;k=e.$dropdown;a.eventBus.listen(j.suggestionClicked,function(a){b.logDebug("Suggestion clicked",a);f(a.suggestion.data("url"));l.submit()});a.eventBus.listen(j.noSuggestions,function(a){d(a)});a.eventBus.listen(j.suggestionsReadyForDisplay,function(a){a.suggestions.length===2&&a.suggestions[1].type==="separator"&&a.suggestions[0].isExactMatch===!0?(a=k.find(g.suggestionClass).eq(0),
f(a.data("url"))):a.searchTerm.length>=4?d(a.searchTerm):c(i.submitId).attr("disabled","disabled")});a.eventBus.listen(j.hideDropdown,function(){k.hide()})}});h.$Nav.when("sx.iss.utils","sx.iss.Events","sx.iss.TimingEvents","sx.iss.MetricsLogger").build("sx.iss.SuggestionAggregator",function(c,a,b,g){return function(e,j){function i(d){c.timingProvider.startTimer(b.latency.group,b.latency.events.timeToDisplay);g.startEndToEndLogging();if(!f[d]){f[d]={remainingProviders:e.length,searchTerm:d,suggestionSets:{}};
for(var i=0;i<e.length;i++){var n=a.createEvent(e[i],j.suggestionsNeeded);c.eventBus.trigger(n,d)}}}function d(a){var b=f[a.searchTerm],a=a.suggestionSets,d;for(d in a)a.hasOwnProperty(d)&&(b.suggestionSets[d]=a[d]);--b.remainingProviders||(delete f[b.searchTerm],c.eventBus.trigger(j.suggestionsReady,b))}var f={};(function(){for(var b=0;b<e.length;b++){var f=a.createEvent(e[b],j.suggestionsReady);c.eventBus.listen(f,d,this)}c.eventBus.listen(j.suggestionsNeeded,i,this)})()}});h.$Nav.when("$","sx.iss.utils",
"sx.iss.SuggestionTypes").build("sx.iss.SuggestionSequencer",function(c,a,b){return function(c){var e=[b.department.name,b.a9Corpus.name,b.a9XOnly.name,b.a9Xcat.name,b.a9.name,"array"],j={type:"separator"};this.sequence=function(a){for(var b=a.suggestionSets,a=[],f=0,l=this.isDeepNode(c),k=0;k<e.length;k++){var n=b[e[k]];if(!(typeof n==="undefined"||n.length===0)){for(var h=0;h<n.length&&f<10;h++){var p=n[h];p.dispIdx=a.length;a.push(p);f++}f>0&&!l&&a.push(j)}}l&&(a=this.sequenceDeepNodeResults(a));
b=a.length;b>0&&a[b-1].type==="separator"&&a.splice(-1,1);return a};this.isDeepNode=function(b){var d,f;b.deepNodeISS&&(d=a.suggestionUtils.getDeepNodeAlias(b.deepNodeISS),f=a.suggestionUtils.getDeepNodeCategoryName(d,b.deepNodeISS));return d!==q&&f!==q};this.sequenceDeepNodeResults=function(a){for(var d,f,e=[],c=0;c<a.length;c++)f=a[c],(d===b.a9Xcat.name||d===b.a9XOnly.name)&&f.type===b.a9.name?e.unshift(f):e.push(f),d=f.type;return e}}});h.$Nav.when("$","sx.iss.utils","sx.iss.Events","NavDomApi").build("sx.iss.MetricsLogger",
function(c,a,b,g){function e(){var a=g.isSearchBoxFocused()?l:f;ue.tag(a)}function j(){uet(k,d,p);uet(n,d,p);uex(h,d,p)}function i(){return typeof uet==="function"&&typeof uex==="function"}var d="iss-init-pc",f="iss-on-time",l="iss-late",k="cf",n="be",h="ld",p={wb:1};i()&&(a.eventBus.listen(b.globals.initializeNavSearchBox,e),a.eventBus.listen(b.globals.issLoaded,j));return{startEndToEndLogging:function(){i()&&uet("bb","iss-end-to-end-a9",p)},stopEndToEndLogging:function(){i()&&(uet(k,"iss-end-to-end-a9",
p),uet(n,"iss-end-to-end-a9",p),uex(h,"iss-end-to-end-a9",p))}}});h.$Nav.when("$","sx.iss.utils","sx.iss.TimingEvents","sx.iss.SuggestionTypes","sx.iss.SearchBoxEventHandler","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.DesktopSearchBoxEventHandler","NavDomApi","sx.iss.Events","sx.iss.Reftag",
"sx.iss.Weblab","sx.iss.DebugUtils","sx.iss.MetricsLogger").build("sx.iss.IssParentCoordinator",function(c,a,b,g,e,j,i,d,f,l,k,n,h,p,m,o,x,w,s,u){return function(t){function I(a){var b={provider:new f(a.name,a.templateId)};return a===g.a9Xcat||a===g.a9XOnly?c.extend(b,{partials:[{key:"storeHtml",provider:new f(a.name,"s-storeText"),formatter:{string:t.deptText,toReplace:"{department}"}}]}):b.provider}var B,q,Q=!1;s.isQIAEnabled()&&c.extend(t,{cf:1});q={$form:m.getForm(),$dropdown:m.getDropdown(),
$searchbox:m.getSearchBox()};B=o.createInstance();m.getForm().data("originalSearchTerm",m.getKeyword());m.getForm().data("originalAlias",m.getAliasFromDropdown());(function(){new e(t,q,B);n.init();var b=[(new j("desktop",t,B)).getName()],c=[I(g.a9),I(g.a9Corpus),new f("separator","s-separator"),I(g.a9Xcat),I(g.a9XOnly)];if(t.hasOwnProperty("isDigitalFeaturesEnabled")&&t.isDigitalFeaturesEnabled===1){c.push(new f(g.department.name,g.department.templateId));var s=new i(t,B);b.push(s.getName())}new k("suggestions-template",
new l(t),c,B,t);new d(b,B);a.eventBus.trigger(o.globals.initializeNavSearchBox);b=new p(B,t);new x(B,t,{shouldAddImeTag:b.getWasCompositionUsed});new h(B,m.getDropdown());new w(t,B)})();a.eventBus.listen(B.suggestionsReadyForDisplay,function(d){Q&&(q.$searchbox.val().length===0?s.logDebug('Search term is empty, abort rendering for the search term "'+d.searchTerm+'"'):(m.showDropdown(d.display),a.timingProvider.stopTimer(b.latency.group,b.latency.events.timeToDisplay),u.stopEndToEndLogging(),a.eventBus.trigger(B.suggestionsRendered,
d),a.eventBus.trigger(o.globals.suggestionsRendered,d)))});a.eventBus.listen(B.hideDropdown,function(){Q=!1});a.eventBus.listen(B.suggestionsNeeded,function(){Q=!0})}});h.$Nav.when("$","sx.iss.utils","sx.iss.SearchBoxEventHandler","sx.iss.SuggestionAggregator","sx.iss.SuggestionDisplayProvider","sx.iss.SuggestionSequencer","sx.iss.IssDisplayProvider","sx.iss.TemplateInstaller","sx.iss.SuggestionEventHandler","sx.iss.Events","sx.iss.DomUtils","sx.iss.ArraySuggestionProvider","sx.iss.CustomSearchBoxEventHandler").build("sx.iss.CustomParentCoordinator",
function(c,a,b,g,e,j,i,d,f,l,k,n,h){return function(p){var m,o;(function(){d.init();m=l.createInstance();var a=p.searchboxId,w=c(p.formId),s=c('<div id="search-dropdown-custom" class="search-dropdown"></div>');w.after(s);o={$form:w,$dropdown:s,$searchbox:c(a)};o.$dropdown.css({width:o.$searchbox.outerWidth()});new b(p,o,m);new f(m,o.$dropdown);new h(o,m,p);p.hasOwnProperty("src")&&k.isArray(p.src)&&(a=new n(p.src,m),new g([a.name],m));a=[new e("array","s-minimal")];new i("suggestions-template",new j(p),
a,m,p)})();a.eventBus.listen(m.suggestionsReadyForDisplay,function(b){o.$dropdown.html(b.display);o.$dropdown.show();a.eventBus.trigger(m.suggestionsRendered,b)});return{dropdownId:"search-dropdown-custom"}}});h.$Nav.importEvent("jQuery",{as:"$",global:"jQuery"});h.$Nav.when("$","sx.iss.utils","sx.iss.Events","sx.iss.A9SuggestionProvider","sx.iss.DepartmentSuggestionProvider","sx.iss.A9SearchSuggestionEventHandler","sx.iss.HelpSuggestionProvider","sx.iss.RecentSearchSuggestionProvider","sx.iss.RecentSearchSuggestionEventHandler",
"sx.iss.SuggestionHighlightingProvider","sx.iss.SuggestionAggregator","sx.iss.SuggestionSequencer","sx.iss.SuggestionDisplayProvider","sx.iss.IssDisplayProvider","sx.iss.IssParentCoordinator","sx.iss.PublicApi","sx.iss.MetricsLogger","sx.iss.CustomParentCoordinator").build("sx.iss",function(c,a,b,g,e,j,i,d,f,l,k,n,h,p,m,o,x,w){g={Events:b,A9SuggestionProvider:g,DepartmentSuggestionProvider:e,A9SearchSuggestionEventHandler:j,HelpSuggestionProvider:i,RecentSearchSuggestionProvider:d,RecentSearchSuggestionEventHandler:f,
SuggestionHighlightingProvider:l,SuggestionAggregator:k,SuggestionSequencer:n,SuggestionDisplayProvider:h,IssDisplayProvider:p,IssParentCoordinator:m,CustomParentCoordinator:w,IssParentCoordinatorMobile:m,SuggestionSequencerMobile:n,isNewIss:!0};c.extend(g,g,o);a.eventBus.trigger(b.globals.issLoaded);return g});h.$Nav.when("sx.iss").run(function(c){h.$Nav.publish("sx.iss",c);h.$Nav.publish("search-js-autocomplete",c)})})})(function(){var y=window.AmazonUIPageJS||window.P,h=y._namespace||y.attributeErrors;
return h?h("RetailSearchAutocompleteAssets"):y}(),window);
/* ******** */
(function(b,e,i){b.execute(function(){function n(d){d.searchCSL=new function(){var c=this,b=[],f=[],j,k,l,g,h=200,m;c.init=function(a,b,d){a&&b&&!j&&(j=a,c.updateRid(b),d&&(h=d))};c.updateRid=function(a){a&&k!=a&&(c.tx(),k=a,l={})};c.addWlt=function(a){if(a){if(a.call&&(a=a(),!a))return;l[a]||(b.push(a),l[a]=1,c.scheduleTx())}};c.addAmabotPrerendered=function(a){a&&a.rid&&a.selections&&a.selections.length&&(f.push(a),c.scheduleTx())};c.scheduleTx=function(){if(h==0)c.tx();else{if(!m){var a=e.onbeforeunload;
e.onbeforeunload=function(b){g&&(e.clearInterval(g),g=i);c.tx();m=!1;return a&&a.call?a(b):i};m=!0}!g&&h>0&&(g=e.setTimeout(function(){g=i;c.tx()},h))}};c.tx=function(){if(b.length||f.length){var a="/mn/search/csl?";b.length&&(a+="rrid="+k+"&cpt="+j+"&ctw="+b.join("|"),b=[]);if(f.length){var c="";d.each(f,function(a,b){c+=b.rid+":";d.each(b.selections,function(a,d){d&&(c+=d+(a!=b.selections.length-1?",":""))});c+=a!=f.length-1?".":""});f=[];c&&(a+=a.charAt(a.length-1)=="?"?"":"&",a+="amabotSelections="+
c)}(new Image).src=a}}};return d.searchCSL}if(e.$Nav){if(!e.$SearchJS)e.$SearchJS=$Nav.make("sx");$SearchJS.importEvent("jQuery",{as:"$",global:"jQuery"});$SearchJS.importEvent("jQuery",{global:"jQuery"});$SearchJS.when("jQuery").run("searchCSL-lib",function(b){b.searchCSL=b.searchCSL||n(b);$SearchJS.publish("search-csl",b.searchCSL)})}else b&&b.when("jQuery").execute(function(d){try{b.register("search-csl",function(){return n(d)})}catch(c){}})})})(function(){var b=window.AmazonUIPageJS||window.P,
e=b._namespace||b.attributeErrors;return e?e("RetailSearchClientSideLoggingAuiAssets"):b}(),window);
/* ******** */
(function(c,j,p){c.execute(function(){(function(){c.register("p13n-sc-math",function(){return Math});c.register("p13n-sc-document",function(){return document});c.register("p13n-sc-window",function(){return j});c.register("p13n-sc-undefined",function(){});var b=function(){return j.P&&j.P.AUI_BUILD_DATE};b()?(c.when("jQuery").register("p13n-sc-jQuery",function(b){return b}),c.when("ready").register("p13n-sc-ready",function(){})):j.amznJQ&&(j.amznJQ.available("jQuery",function(){c.register("p13n-sc-jQuery",
function(){return j.amznJQ.jQuery})}),j.amznJQ.onReady("jQuery",function(){c.register("p13n-sc-ready",function(){})}),j.amznJQ.available("amazonShoveler",function(){c.register("p13n-sc-amznJQ-shoveler",function(){})}));c.when("p13n-sc-window").register("p13n-sc-util",function(d){var i=d.ueLogError;typeof i!=="function"&&(i=function(b,d){if(d&&d.message)throw Error(d.message);if(b&&b.message)throw Error(b.message);});var e=function(b,d){i({logLevel:b,attribution:"P13NSharedSitewideJS",message:"[p13n-sc] "+
d})};return{constants:{DATA_ATTR_P13N_FEATURE_NAME:"p13nFeatureName"},count:d.ue&&d.ue.count||function(){},isAUI:b,log:{warn:function(b){e("WARN",b)},error:function(b){e("ERROR",b)}}}})})();c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-undefined").register("p13n-sc-heartbeat",function(b,d,i){var e=d.clearInterval,h={},n,c,a=function(){if(!n){var a=d.setInterval(function(){var f=a,b=(new Date).getTime();f!==n?e(f):((!c||b-c>200)&&g(),c=(new Date).getTime())},200);n=a}},g=function(){b.each(h,function(a,
b){b.call(d)})};return{subscribe:function(b,f){h[b]||(h[b]=f,a())},unsubscribe:function(a){h[a]&&delete h[a];var a=!0,b;for(b in h)h.hasOwnProperty(b)&&(a=!1);a&&(e(n),n=i)}}});c.when("p13n-sc-jQuery","p13n-sc-heartbeat").register("p13n-sc-call-on-visible",function(b,d){var i=[],e=b(j),h=function(){for(var b=e.scrollTop()+e.height(),h=e.scrollLeft()+e.width(),a=i.length-1;a>=0;a--){var g=i[a],k=g.callback,f=g.$element,c=g.distanceY,g=g.distanceX;if(f.parents("body").size()===0)i.splice(a,1);else if(!f.is(":hidden")){var o=
f.offset();b-c>o.top&&h-g>o.left&&(k.call(null,f[0]),i.splice(a,1))}}i.length===0&&d.unsubscribe("p13n-sc-call-on-visible")};return{register:function(e,c,a){var g=a&&typeof a.distance!=="undefined"?a.distance:0,k=a&&typeof a.distanceY!=="undefined"?a.distanceY:g,f=a&&typeof a.distanceX!=="undefined"?a.distanceX:0;b(e).each(function(){i.push({$element:b(this),callback:c,distanceY:k,distanceX:f})});d.subscribe("p13n-sc-call-on-visible",h);h()}}});c.when("A","jQuery","p13n-sc-call-on-visible","p13n-sc-util",
"p13n-sc-math").register("p13n-sc-view-trigger",function(b,d,i,e,h){var n=function(a){var g=d(a),a=g.attr("data-params"),k=g.attr("data-url");if(a&&k){var a=b.parseJSON(a),f=g.offset(),g=[f.top,f.left,g.height(),d(j).width()];a.elementRect=g.join(",");var e=0,i={cache:!0,crossDomain:!1,data:d.param(a,!1),error:function(a){a=a.status||0;e>=3||a>=400&&a<500||setTimeout(c,200*h.pow(2,e))},global:!1,url:k},c=function(){e+=1;d.ajax(i)};c()}},l=function(a){var g=d(a);if(g.size()===1){var k=g.attr("data-params"),
k=k?b.parseJSON(k):{};if(!(k.allowEmpty!==!0&&d.trim(g.text()).length===0)){var f=g.height();if(!(k.allowEmpty!==!0&&f<5)){f=0;if(typeof k.distance==="number")f=k.distance;g.attr("data-p13n-sc-vt-initialized")||(g.attr("data-p13n-sc-vt-initialized",!0),i.register(a,function(){n(a)},{distance:f}))}}}},e=function(){b.each(d(".p13n-sc-vt:not([data-p13n-sc-vt-initialized])"),function(a){l(a)})};c.execute(e);c.when("afterReady").execute("p13n-sc-view-trigger:init",e);return{initializeElement:l}});c.when("p13n-sc-jQuery",
"p13n-sc-util","p13n-sc-window","p13n-sc-document","p13n-sc-ready").register("p13n-sc-logger",function(b,d,i,e){function h(a){return a.join("")}function c(a,b){var f=a.attr(b),k={};f!==p&&f!==null&&(k=typeof i.JSON!=="undefined"?JSON.parse(f):eval("("+f+")"));return k}function l(a,f){for(var k=[a.widget,":"],g=0;g<a.asins.length;g++){var d=a.asins[g];k.push(d.asin,"@");b.each(d,function(a,m){a!=="asin"&&k.push(a,"=",m,"|")});k.splice(k.length-1,1);k.push(",")}a.asins.length>0&&k.splice(k.length-1,
1);f&&(k.push(":","action=",a.action),b.each(a.meta,function(a,m){k.push(",",a,"=",m)}));return h(k)}function a(a,f){var k=c(b(f),"data-p13n-asin-metadata");if(k&&k.asin){var g=k.asin,d=c(b(a),"data-p13n-asin-metadata");d&&b.extend(!0,k,d[g]);return k}}function g(a,k){var g=new Image;d.count("p13n:logger:attempt",1);g.onerror=function(){f++;d.count("p13n:logger:error",1)};g.src=h(["https:"===e.location.protocol?"https://":"http://",i.ue_furl||"fls-na.amazon.com","/1/","p13n-shared-components","/1/OP/p13n/",
k,h(["?",b.param(c(b(a.featureElement),"data-p13n-global"))])])}function k(){return f>3?(q||(d.log.warn("impression image load failed too many times, no longer logging impressions"),d.count("p13n:logger:abort",1),q=!0),!0):!1}var f=0,q=!1,o={},j={},r={logAction:function(m){if(!k())if("featureElement"in m)if("action"in m){var f=b(m.featureElement);m.asins=b.map(b(m.featureElement).find(".p13n-asin").filter(":visible"),function(m){return a(f,m)});m.meta=m.meta||{};var e=c(f,"data-p13n-feature-metadata");
b.extend(!0,m.meta,e);m.widget=f.attr("data-p13n-feature-name");m.widget in o||(o[m.widget]={});if(m.asins.length!==0){for(var i=e=0;i<m.asins.length;i++)m.asins[i].asin in o[m.widget]||(o[m.widget][m.asins[i].asin]=!0,e++);m.logOnlyOnNew&&e===0||(e=h(["action/",h([m.widget,"_:",m.action,"@v=",m.eventtime||0,",impressed@v=",e]),"/",l(m,!0)]),m.replicateAsinImpressions&&(i=h(["asin/",l(m,!1)]),e=h(["batch/",e,"$",i])),g(m,e))}}else d.log.warn("action missing in eventData for logAction");else d.log.warn("featureElement missing in eventData for logAction")},
logAsyncAction:function(a){var f=(new Date).getTime(),k=typeof a.initialDelay==="number"?a.initialDelay:400,g=typeof a.timeout==="number"?a.timeout:5E3,d=b(a.featureElement);a.widget=d.attr("data-p13n-feature-name");a.widget in j&&i.clearTimeout(j[a.widget]);var h=function(){var b=a.isEventComplete(),k=(new Date).getTime();if(k-f<g&&!b)j[a.widget]=i.setTimeout(h,150);else{if(!b){if(!("meta"in a))a.meta={};a.meta.err="notfinished"}a.eventtime=k-f;delete j[a.widget];r.logAction(a)}};j[a.widget]=i.setTimeout(h,
k)},eventPending:function(a){return b(a).attr("data-p13n-feature-name")in j},impressAsin:function(m){if(!k())if("featureElement"in m)if("faceoutElement"in m){var f=b(m.faceoutElement),e=b(m.featureElement);m.widget=e.attr("data-p13n-feature-name");m.asins=[a(e,f)];f=h(["asin/",l(m,!1)]);g(m,f)}else d.log.warn("faceoutElement missing in eventData for logAction");else d.log.warn("featureElement missing in eventData for logAction")}};return r});c.when("jQuery","A","p13n-sc-call-on-visible","p13n-sc-logger",
"ready").register("p13n-sc-faceout-logger",function(b,d,i,e){var h=function(d,h){var a=b(d),g=b(h);a.length===1&&!a.attr("data-p13n-sc-fl-initialized")&&(a.attr("data-p13n-sc-fl-initialized",!0),i.register(a,function(){e.impressAsin({featureElement:g,faceoutElement:a})}))};d.on("p13n:faceoutsloaded",function(d){b(d).find(".p13n-asin:not([data-p13n-sc-fl-initialized])").each(function(b,a){h(a,d)})})});c.when("A","jQuery").register("p13n-sc-lazy-image-loader",function(b,d){return{loadImages:function(i){b.executeDeferred();
i.find(".p13n-sc-lazy-loaded-img").each(function(e,h){var i=d(h),c=i.find(".a-dynamic-image");c.load(function(){i.removeClass("p13n-sc-lazy-loaded-img")});b.loadDynamicImage(c)})}}});c.when("p13n-sc-jQuery","p13n-sc-util","p13n-sc-math").register("p13n-sc-line-truncator",function(b,d,i){function e(a){this.$element=a;this.$experimentElement=b("<div>").addClass("p13n-sc-offscreen-truncate");this.maxRows=a.attr("data-rows");this.lineHeight=this.getLineHeight();this.maxRows||d.log.error("Truncation element missing necessary line number data")}
var h=/(?=[ \-\/])/,n=/[^\/\-\[\]():\s]/;e.prototype.truncate=function(){var a=this.$element.html(),a=b.trim(a);this.$element.append(this.$experimentElement);if(!this.checkLineFit(a)){var g=this.truncateByToken(a);g?(this.$element.html(g),this.$element.attr({title:a})):d.log.error("Unable to successfully truncate line "+a)}this.$experimentElement.remove()};e.prototype.getLineHeight=function(){var a=this.$element.text();this.$element.html("&hellip;");var b=this.$element.innerHeight();this.$element.html(a);
return b};e.prototype.checkLineFit=function(a){this.$experimentElement.html(a);a=this.$experimentElement.get(0).clientHeight/this.lineHeight;return i.round(a)<=this.maxRows};e.prototype.truncateByToken=function(a){for(var a=a.split(this.getTokenSeparatorRegex()),b=1,k=a.length,f,d,h=0;b!==k;)if(f=i.floor((k+b)/2),d=a.slice(0,f).join("")+"&hellip;",this.checkLineFit(d)){if(k-f<=1){for(h=f;h>0&&!n.test(a[h-1]);)h--;break}b=f}else k=f;return h===0?void 0:a.slice(0,h).join("")+"&hellip;"};e.prototype.getTokenSeparatorRegex=
function(){return this.$element.attr("data-truncate-by-character")?"":h};var l=function(){};c.when("A").execute("trigger-linestruncated",function(a){l=function(){a.trigger("p13n:linestruncated")}});return{truncateLines:function(a){a.find(".p13n-sc-truncate:visible").each(function(){var a=new e(b(this));a&&(a.truncate(),b(this).addClass("p13n-sc-truncated").removeClass("p13n-sc-truncate"),b(this).removeClass(function(a,b){return(b.match(/p13n-sc-line-clamp-\d/g)||[]).join(" ")}))});l()}}});c.when("A",
"jQuery","a-carousel-framework","p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","ready").execute("p13n-sc-carousel-logger",function(b,d,i,e,h,c){function l(a,b){var g=a.getAttr("pageNumber"),e=a.dom.$container;e.data("p13nPreviousPage",g);h.logAsyncAction(d.extend(!0,{},{featureElement:e,isEventComplete:function(){return e.find(".a-carousel-card-empty").size()===0&&!a.getAttr("animating")},meta:{p:g},replicateAsinImpressions:!0},b))}function a(a){g(a)&&e.register(a.dom.$container,function(){l(a,
{action:"view"})})}var g=function(a){return typeof a==="undefined"?!1:a.dom.$container.data(c.constants.DATA_ATTR_P13N_FEATURE_NAME)?!0:!1};b.each(i.getAllCarousels(),function(b){b.dom.$container.hasClass("a-carousel-initialized")&&a(b)});b.on("a:carousel:init",function(b){a(b.carousel)});d(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-nextpage","click",function(a){a=i.getCarousel(a.target);l(a,{action:"shovel_right"})});d(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-goto-prevpage",
"click",function(a){a=i.getCarousel(a.target);l(a,{action:"shovel_left"})});d(document).delegate(".a-carousel-container[data-p13n-feature-name] .a-carousel-restart","click",function(a){a=i.getCarousel(a.target);l(a,{action:"start_over",meta:{op:a.dom.$container.data("p13nPreviousPage")}})});b.on("a:carousel:change:pageSize",function(a){a=a.carousel;g(a)&&a.dom.$container.hasClass("a-carousel-initialized")&&l(a,{action:"resize",logOnlyOnNew:!0})})});c.when("p13n-sc-jQuery","p13n-sc-window","p13n-sc-document",
"p13n-sc-call-on-visible","p13n-sc-logger","p13n-sc-util","p13n-sc-amznJQ-shoveler").register("p13n-sc-non-aui-carousel",function(b,d,i,e,h,n){var l=function(a){n.count("p13n-sc-non-aui-carousel:init",1);var f=a.attr("data-widgetname"),g=b("#"+f+"Data");if(g.length!==1)return!1;if(a.attr("data-p13n-sc-carousel-initialized"))return!1;else a.attr("data-p13n-sc-carousel-initialized",!0);var e=g.text().split(","),i=a.find(".shoveler-content > ul"),c="input#"+f+"ShvlState",m=function(){},l=200,v=!1,j=
function(){var m=l;a.find(".p13nimp, .p13n-asin").each(function(){var a=b(this).outerHeight(!0);a>m&&(m=a)});m>l&&(l=m,i.animate({height:m},200,"linear"));v||x()},x=function(){var b=l/2;a.find("a.next-button, a.back-button").css("top",b);v=!0},t=a.find(".shoveler").shoveler(function(a,m){var f="",f=typeof d.JSON!=="undefined"?JSON.parse(g.attr("data-ajax")):eval("("+g.attr("data-ajax")+")");f.asins=e.slice(a,a+m).join(",");f.count=m;f.offset=a;f=b.param(f);return g.attr("data-url")+"?"+f},e.length,
{cellTransformer:function(a){return a===null?"":a},cellChangeSpeedInMs:30,preloadNextPage:!0,prevButtonSelector:"a.back-button",nextButtonSelector:"a.next-button",startOverSelector:"span.start-over",startOverLinkSelector:"a",horizPadding:14,state:{ready:function(){return b(c).val().length>0},get:function(){return parseInt(b(c).val(),10)},set:function(a){b(c).val(a)}},onUpdateUIHandler:function(){j();m()}}),w=0,y=function(){var a=b(d).width();w!==a&&(t.updateUI(),w=a)},p=null;a.resize(function(){p&&
d.clearTimeout(p);p=d.setTimeout(y,100)});var u=function(m){h.logAsyncAction(b.extend(!0,{},{featureElement:a,isEventComplete:function(){return a.find("li.shoveler-cell.shoveler-progress").size()===0},replicateAsinImpressions:!0},m))};u({action:"view",meta:{p:t.getCurrentPage()+1}});a.find(".back-button").click(function(){u({action:"shovel_left",meta:{p:t.getCurrentPage()+1}})});a.find(".next-button").click(function(){u({action:"shovel_right",meta:{p:t.getCurrentPage()+1}})});a.find(".start-over-link").mousedown(function(){u({action:"start_over",
meta:{p:1,op:t.getCurrentPage()+1}})});m=function(){h.eventPending(a)||u({action:"resize",page:t.getCurrentPage()+1,logOnlyOnNew:!0,initialDelay:2E3})}},a=function(a){var f={distanceY:-250,distanceX:0};b(a).find(".p13n-sc-nonAUI-carousel").andSelf().filter(".p13n-sc-nonAUI-carousel").each(function(a,d){e.register(d,function(){l(b(d))},f)})},g=function(){a(i)};g();c.when("p13n-sc-ready").execute("p13n-sc-non-aui-carousel:readyInit",g);return{init:a}});c.when("p13n-sc-jQuery","p13n-sc-util").execute("p13n-sc-carousel-initialization-setup",
function(b,d){d.isAUI()?c.when("a-carousel-framework").register("p13n-sc-carousel-init",function(b){return{init:function(){b.createAll()}}}):c.when("p13n-sc-non-aui-carousel").register("p13n-sc-carousel-init",function(b){return{init:function(d){b.init(d)}}})})})})(function(){var c=window.AmazonUIPageJS||window.P,j=c._namespace||c.attributeErrors;return j?j("P13NSharedSitewideJS"):c}(),window);
/* ******** */
(function(c){c.execute(function(){c.when("jQuery","afterLoad","socratesEnabled").register("socr-nav-bootstrap",function(d){function e(a){d.ajax({url:"//"+a+"/gp/socrates/assets/bootstrap-digest",dataType:"json"}).done(function(b){if(b&&b.digest&&d.type(b.digest)==="string"&&(b=b.digest.trim(),b.match(f))){var e="//"+a+"/gp/socrates/assets/bootstrap";b.match(f)&&c.load.js(e+"-"+b+".js")}})}var f=/[a-z0-9]{32}/;c.execute(function(){d.ajax({url:"/gp/socrates/bootstrap/assetdomain",dataType:"json"}).done(function(a){a&&
a.domain&&d.type(a.domain)==="string"&&(a=a.domain.trim(),e(a))})})})})})(function(){var c=window.AmazonUIPageJS||P,d=c.attributeErrors;return d?d("SocratesNavBootstrap"):c}());
/* ******** */
