(function(g){g.execute(function(){g.when("A","jQuery","atf").execute(function(c,a){c.on.ready(function(){function r(b,e,c,f,d){a(b).slideToggle(300);a(e).slideToggle(300);a(c).toggleClass("tmmShowPrompt tmmHidePrompt");a(f).toggleClass("tmmShowPrompt tmmHidePrompt");a(d).toggleClass("rotate")}function h(b){b.position();b.width();a(".swatchElement");b.find(".swatchElement").each(function(){a(this).attr("data-width",a(this).width())});a("#formats").find(".a-row").removeClass("nonJSFormats")}function m(){var b=
a("#formats"),e=b.width()-40,c=0;b.find(".swatchElement").each(function(){a(this).is(":visible")&&(c+=a(this).width())});c>e?a(b.find(".swatchElement:visible").get().reverse()).each(function(){var b=0,d=!1;a(this).find(".format").hasClass("a-button-selected")?(b=a(this).prev(".swatchElement").width(),d=a(this).prev(".swatchElement").is(":hidden"),a(this).prev(".swatchElement").hide()):(b=a(this).width(),d=a(this).is(":hidden"),a(this).hide());d||(c-=b);return c>e}):c<e&&b.find(".swatchElement").each(function(){if(a(this).is(":hidden"))return a(this).attr("data-width")<=
e-c&&a(this).show(),!1})}var o=0,p=0,n,q=function(a){typeof a!="undefined"&&(n=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};typeof amznJQ!="undefined"?amznJQ.available("DPClientLogger",function(){q(window.DPClientLogger)}):g.when("DPClientLogger").execute(q);c.declarative("tmm-see-more-editions-click",["click"],function(b){var e=b.data,d=e.metabindingUrl;if(!b.$target.hasClass("a-link-expander")&&!b.$target.parent().hasClass("a-link-expander")){if(d!=="#")window.location=d}else{var e=
e.metabindingPlaceHolder,f="#metabinding_row_top_"+e,g="#metabinding_row_bottom_"+e,j="#editionsSeePrompt_"+e,h="#editionsHidePrompt_"+e,k="#editionsIcon_"+e,v="isAjaxComplete_"+e,u="isAjaxInProgress_"+e,b="#tmmSpinnerDiv_"+e,i=c.state("mediamatrix-state"),e=i["url_"+e].replace(/&amp;/g,"&");a("#formats .tmmErrorClass").hide();i[v]==="1"||i[u]==="1"?r(f,g,j,h,k):(c.ajax(e,{method:"get",success:function(){i[v]="1";c.state("mediamatrix-state",i);r(f,g,j,h,k)},indicator:a(b),error:function(){a($tmmErrorDiv).show();
i[u]="0";c.state("mediamatrix-state",i)}}),i[u]="1",c.state("mediamatrix-state",i))}});if(a("#formats > .a-link-expander").length>0){var d=window.ue;d&&d.count&&d.count("mediaMatrixExpanderPresent",1)}a("#formats > .a-link-expander").click(function(){r("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt","#formatsIcon");if(!p){var b=window.ue;b&&b.count&&b.count("mediaMatrixExpanderClicked",1);p=1}n&&a("#twister").is(":visible")&&!o&&(n.logImpression("tmm-show-more-formats-viewed"),
o=1)});var d=c.state("mediamatrix-state"),l="1";typeof d!=="undefined"&&typeof d.showHybridMediaMatrix!=="undefined"&&d.showHybridMediaMatrix==="1"?l="0":typeof d!=="undefined"&&typeof d.isDvdWeblabEnabled!=="undefined"&&d.isDvdWeblabEnabled==="1"&&(l="0");l==="1"&&(a("#formats.responsive").each(function(){h(a(this))}),m(),c.on("resize",m));a("#formats .unselected .format").mouseenter(function(){a(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){a(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});
a("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})});g.when("A","jQuery","a-dropdown").execute(function(c,a,g){function h(a){return a?a.replace(/&#0/g,"&#"):undef}function m(a){for(var b=a.getOptions(),b=b?b.size():0,c=1;c<b;c++)a.removeOption(1)}function o(b,c){var e=b.getOption(0),d=e.info()[0];e.remove();a.each(c,function(a,c){b.addOption({text:w[h(c)],value:c,css_class:"dropdownAvailable"},1)});b.addOption(d,0);b.val(d.value)}function p(a){j=
a.value;m(k);j!=="-1"&&(n(),o(k,Object.keys(l[h(j)])))}function n(){if(!Object.keys)Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,constructor".split(","),e=c.length;return function(d){if(typeof d!=="object"&&(typeof d!=="function"||d===null))throw new TypeError("Object.keys called on non-object");var g=[],f;for(f in d)a.call(d,f)&&g.push(f);if(b)for(f=
0;f<e;f++)a.call(d,c[f])&&g.push(c[f]);return g}}()}function q(a){t=a.value;if(!(t==="-1"||j==="-1"))window.location=e[l[h(j)][h(t)]]}function d(a){a=a.value;if(a!=="-1")window.location=e[h(a)]}var l,b=c.state("dcdMetaData");if(b){var e=b.asinToDetailPageURLMap,w=b.truncatedValuesMap,f=b.dimensionKeys,s=f[0],j=-1,t=-1,k;f.length===2?(l=b.doubleValuesToAsinMap,b=f[1],f=g.getSelect("native_dcd_dropdown_"+s),k=g.getSelect("native_dcd_dropdown_"+b),f.setValue("-1"),k.setValue("-1"),m(k),c.on("a:dropdown:selected:"+
s,p),c.on("a:dropdown:selected:"+b,q)):(f=g.getSelect("native_dcd_dropdown_"+s),(g=b.selectedAsin)?f.setValue(g):f.setValue("-1"),c.on("a:dropdown:selected:asin-redirect",d))}})})})(function(){var g=window.AmazonUIPageJS||P,c=g.attributeErrors;return c?c("TwisterHardlinesDetailPageAsset"):g}());
/* ******** */
(function(d){d.execute(function(){d.when("A","jQuery","atf").execute(function(f,a){function d(){var b=parseInt(a("#byline").width()),e=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(e+=a(this).outerWidth())});e+=a("#byline .more").outerWidth();if(e>b){var f=a("#byline .author.notFaded").length;a(a("#byline .author.notFaded").get().reverse()).each(function(c){e>b&&c<f-1&&(c=a(this).width(),a(this).removeClass("notFaded"),a(this).fadeOut(10,function(){a(this).hide()}),e-=c,a("#byline .moreCount").html(a("#byline .author").length-
a("#byline .author.notFaded").length),a("#byline .more").addClass("notFaded").fadeIn(10))})}else if(e<b&&a("#byline .author.notFaded").length<a("#byline .author").length){var g=b-e;a("#byline .author").each(function(){if(!a(this).hasClass("notFaded")){var c=a(this).outerWidth();c<=g?(g-=c,a(this).addClass("notFaded").fadeIn(10),c=a("#byline .author").length-a("#byline .author.notFaded").length,c===0?a("#byline .more").removeClass("notFaded").fadeOut(10):(a("#byline .moreCount").html(c),a("#byline .more").addClass("notFaded").fadeIn(10))):
g=0}})}}a("#byline .showMoreLink").click(function(){a("#byline .author").each(function(){a(this).hasClass("notFaded")||a(this).addClass("notFaded").fadeIn(0);a("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});a("#byline .contributorNameID").mouseenter(function(){var b=a(this).attr("data-asin"),e={},d="isAjaxComplete_"+b,g="isAjaxInProgress_"+b,c=f.state("popoverImage-state");e.entityID=b;c[d]!=="1"&&c[g]!=="1"&&(a.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",
data:e,dataType:"html",timeout:1E3,success:function(e){a("#contributorImageContainer"+b).get(0).innerHTML=e;c[d]="1";f.state("popoverImage-state",c)},error:function(){c[g]="0";f.state("popoverImage-state",c)}}),c[g]="1",f.state("popoverImage-state",c))});(function(b){var e=parseInt(b.width()),d=parseInt(b.find(".more").outerWidth()),g=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(g+=a(this).outerWidth())});a("#byline .more").attr("data-width",d);var c=e-d;if(c>g)b.find(".author").each(function(){var b=
a(this).index();parseInt(b)>=3?(b=a(this).outerWidth(),a(this).attr("data-width",b),b<c?(c-=b,a(this).addClass("notFaded"),a(this).fadeIn("slow")):(c=0,a(this).fadeOut("slow"))):(b=a(this).outerWidth(),a(this).attr("data-width",b),c-=b)});else{var f=a("#byline .author.notFaded").length;a(a("#byline .author.notFaded").get().reverse()).each(function(b){c<g&&b<f-1&&(b=a(this).outerWidth(),g-=b,a(this).fadeOut("slow").removeClass("notFaded"))})}e=b.find(".author").length-b.find(".author.notFaded").length;
e>0&&(b.find(".moreCount").html(e),b.find(".more").fadeIn("slow"),b.find(".more").addClass("notFaded"))})(f.$("#byline"));a(window).resize(function(){d()})});d.when("A","jQuery").register("product-description-fix",function(d,a){return{fixTableIssue:function(){a("#productDescription .productDescriptionWrapper table").each(function(){var d=a(this).attr("width");typeof d!=="undefined"?a(this).css("width",d):a(this).css("width","auto")})}}})})})(function(){var d=window.AmazonUIPageJS||P,f=d.attributeErrors;
return f?f("PInfoHardlinesDetailPageAsset"):d}());
/* ******** */
(function(c){c.execute(function(){c.when("A","jQuery","atf").register("accordionBuyBoxJS",function(c,a){var d={updateCssClass:function(b){var c=a("#rbbContainer");c.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");c.find(".selected .offer-price").removeClass("a-color-price").addClass("a-color-secondary");b.parents(".rbbSection").removeClass("unselected").addClass("selected");b.parents(".rbbSection").toggleClass("dp-accordion-active",500);
b.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");b.find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price");a("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-secondary").addClass("a-color-price")},animate:function(b){var c=a("#rbbContainer"),d=b.attr("id"),e,f;c.find(".rbbSection").each(function(b,c){a(c).find(".rbbHeader")[0].id==d?e=a(c):a(c).hasClass("selected")&&(f=a(c))});f.find(".rbbContent").slideUp(500,
function(){f.removeClass("selected").addClass("unselected");f.toggleClass("dp-accordion-active",500)});e.find(".rbbContent").slideDown(500);a.browser.msie&&parseInt(a.browser.version,10)==7&&(e.find(".rbbContent").css("display","inline"),setTimeout(function(){e.find(".rbbContent").css("display","block")},505))},oneClickJS:function(){a("#one-click-button, #one-click-button-ubb").click(function(){var b="https://"+window.location.host+a("#addToCart").attr("action");a("#addToCart").attr("action",b);return!0})},
usedBuyBoxJS:function(){a("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var b=a("#addToCart"),c=b.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");b.attr("action",c);return!0});amznJQ.available("popover",function(){a("#usedItemConditionInfoLink").amazonPopoverTrigger({showCloseButton:!1,closeEventInclude:["CLICK_TRIGGER","CLICK_OUTSIDE","MOUSE_LEAVE"],locationElement:a("#usedItemConditionInfoLink"),location:"bottom",width:250,localContent:"#usedItemConditionInfoPopover"})})},
initialize:function(){a(".rbbHeaderLink").attr("href","javascript:void(0);");a("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();a("#rbbContainer .rbbSection .rbbHeader").click(function(b){a(b.target);b=a(this);b=b.hasClass("rbbHeader")?b:b.parents(".rbbHeader");if(b.parents(".rbbSection").hasClass("selected"))return!1;d.updateCssClass(b);a("#abbWrapper [id^=mbb-offeringID-]").each(function(){this.checked=!1});b=a(this);d.animate(b);return!0});d.oneClickJS();d.usedBuyBoxJS()}};return d})})})(function(){var c=
window.AmazonUIPageJS||P,g=c.attributeErrors;return g?g("OffersHardlinesDetailPageAsset"):c}());
/* ******** */
