(function(a,c,p){function m(b){for(var a={},g,u,e=0;e<b.length;e++)u=b[e],g=u.r+u.s+u.m,u.c&&(a[g]||(a[g]=[]),a[g].push(b[e]));return a}function l(b){for(var a=1;a<arguments.length;a++){var g=arguments[a];try{if(g.isSupported)return g.send(b)}catch(u){}}}function j(){for(var a=0;a<w.length;a++)w[a]();v.length&&l(m(v.splice(0,v.length)),E,H,B);F=A=0}function f(b,e,g){g=g||{};0===g.bf&&i.isBF||(b={r:g.r||i.rid,s:g.s||a.ue_sid,m:g.m||a.ue_mid,mkt:g.mkt||a.ue_mkt,sn:g.sn||a.ue_sn,c:e,d:b,t:g.t||i.d(),
cs:g.c&&a.ue_qsl},g.b?l(m([b]),E,B):g.nb?l(m([b]),E,H,B):g.img||G[e]?l(m([b]),B):g.n?(v.push(b),0===z?j():F||(F=c.setTimeout(j,z))):(v.push(b),A||(A=c.setTimeout(j,J))))}function n(b,a,g){C++;C==s?f({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},c.ue_err_chan||"jserr"):C<s&&f(b,a,g)}function h(){if(!x){for(var b=0;b<y.length;b++)y[b]();for(b=0;b<w.length;b++)w[b]();l(m(v.splice(0,v.length)),E,B);x=!0}}var k={};(function(){function b(a){return 10>a?"0"+a:a}function a(b){u.lastIndex=
0;return u.test(b)?'"'+b.replace(u,function(b){var a=o[b];return"string"===typeof a?a:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function g(b,I){var u,o,k,d,N=e,D,r=I[b];r&&"object"===typeof r&&"function"===typeof r.toJSON&&(r=r.toJSON(b));"function"===typeof c&&(r=c.call(I,b,r));switch(typeof r){case "string":return a(r);case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";e+=i;D=[];if("[object Array]"===
Object.prototype.toString.apply(r)){d=r.length;for(u=0;u<d;u+=1)D[u]=g(u,r)||"null";k=0===D.length?"[]":e?"[\n"+e+D.join(",\n"+e)+"\n"+N+"]":"["+D.join(",")+"]";e=N;return k}if(c&&"object"===typeof c)for(d=c.length,u=0;u<d;u+=1)"string"===typeof c[u]&&(o=c[u],(k=g(o,r))&&D.push(a(o)+(e?": ":":")+k));else for(o in r)Object.prototype.hasOwnProperty.call(r,o)&&(k=g(o,r))&&D.push(a(o)+(e?": ":":")+k);k=0===D.length?"{}":e?"{\n"+e+D.join(",\n"+e)+"\n"+N+"}":"{"+D.join(",")+"}";e=N;return k}}"function"!==
typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var u=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,
i,o={"":"\\b","\t":"\\t","\n":"\\n","":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},c;"function"!==typeof k.stringify&&(k.stringify=function(b,a,u){var I;i=e="";if("number"===typeof u)for(I=0;I<u;I+=1)i+=" ";else"string"===typeof u&&(i=u);if((c=a)&&"function"!==typeof a&&("object"!==typeof a||"number"!==typeof a.length))throw Error("JSON.stringify");return g("",{"":b})})})();var d=function(){function b(a,g){if(null==a)return g.push("!n");if("number"===typeof a)return g.push("!"+a);if("string"===typeof a)return"\\"==
a[a.length-1]?g.push("'"+a.replace(/'/g,"\\'")+"u005C'"):g.push("'"+a.replace(/'/g,"\\'")+"'");if("boolean"===typeof a)return g.push(a?"!t":"!f");if(a instanceof Array){g.push("*");for(var u=0;u<a.length;u++)b(a[u],g);return g.push(")")}if("object"==typeof a){g.push("(");for(u in a)a.hasOwnProperty(u)&&(g.push(u),b(a[u],g));return g.push(")")}return g.push("!n")}return{stringify:function(a){var g=[];b(a,g);return g.join("")}}}(),t=a.ue_qsl||2E3,s=1E3,q=function(){},b="",o=c.JSON&&c.JSON.stringify||
k&&k.stringify,e=d.stringify,i=a.ue||{},d=a.uet||q;(a.uet||q)("bb","ue_frst_v2",{wb:1});var r="//"+a.ue_furl+"/1/batch/1/OE/",v=[],y=[],w=[],x=!1,F,A,z=void 0===a.ue_hpfi?1E3:a.ue_hpfi,J=void 0===a.ue_lpfi?1E4:a.ue_lpfi,G={"scheduled-delivery":1},C=0,H=function(){function I(){if(c.XDomainRequest){var a=new XDomainRequest;a.onerror=q;a.ontimeout=q;a.onprogress=q;a.onload=q;a.timeout=0;return a}if(c.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw b;return a}if(c.ActiveXObject){for(var e=
0;e<g.length&&!a;e++)try{a=new ActiveXObject(g[e]),g=[g[e]]}catch(I){}return a}}function e(b){for(var g=[],I=b[0]||{},K=0;K<b.length;K++){var o={};o[b[K].c]=b[K].d;g.push(o)}return{rid:I.r||i.rid,sid:I.s||a.ue_sid,mid:I.m||a.ue_mid,mkt:I.mkt||a.ue_mkt,sn:I.sn||a.ue_sn,reqs:g}}var g="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(a){for(var g in a)if(a.hasOwnProperty(g)&&a[g].length){var i=e(a[g]),c=I();
if(!c)throw b;c.open("POST",r,!0);c.setRequestHeader&&c.setRequestHeader("Content-type","text/plain");c.send(o(i))}},buildPOSTBodyLog:e,isSupported:!0}}(),B=function(){return{send:function(b){for(var K in b)if(b.hasOwnProperty(K)){for(var g=b[K],u=g,M={},c=void 0,k=0;k<u.length;k++)c=u[k].c,M[c]||(M[c]=[]),M[c].push(u[k]);var g=g[0]||{},u=g.sn||a.ue_sn,g=r+(g.m||a.ue_mid)+":"+(g.s||a.ue_sid)+":"+(g.r||i.rid)+(u?":"+u:""),u=[],c=g,k=[],d=void 0;for(d in M)if(M.hasOwnProperty(d))for(var h=0;h<M[d].length;h++){var f=
M[d][h],j=encodeURIComponent((f.cs?e:o)(f.d));k.push({l:j,t:f.t,p:1,c:d,d:f.cs?"c":"j"})}M=k;k=void 0;d="$";for(f=0;f<M.length;){h=M[f];k!=h.c?(c+=d+h.c+"=",d="&",k=h.c):c+=",";var j=c,l=h.d+":",v=h,c=(v.l.match(".{1,"+(t-c.length)+"}[^%]{0,2}")||[])[0]||"";v.l=v.l.substr(c.length);c=j+(l+c+":"+h.t);if(h.l)c+=":"+h.p++ +"_",u.push(c),c=g,d="$",k=0;else if(f++,1!=h.p)for(c+=":"+h.p+"_"+h.p,j=0;j<h.p-1;j++)u[u.length-j-1]+=h.p}u.push(c);g=u;for(u=0;u<g.length;u++)(new Image).src=g[u]}},isSupported:!0}}(),
E=function(){return{send:function(a){for(var e in a)if(a.hasOwnProperty(e)){var g=H.buildPOSTBodyLog(a[e]);if(!navigator.sendBeacon(r,o(g)))throw b;}},isSupported:!!navigator.sendBeacon}}();i._fic=B;i._fac=H;i._fbc=E;i._flq=v;i.sid=i.sid||a.ue_sid;i.mid=i.mid||a.ue_mid;i.furl=i.furl||a.ue_furl;i.sn=i.sn||a.ue_sn;i.isBF=function(){var a=c.performance||c.webkitPerformance,b=p.ue_backdetect&&p.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,g=i.bfini;return a&&a.navigation&&2===a.navigation.type||
1<g||!g&&1<b}();try{c.amznJQ&&c.amznJQ.declareAvailable&&c.amznJQ.declareAvailable("forester-client"),c.P&&c.P.register&&c.P.register("forester-client",q)}catch(P){a.ueLogError(P,{logLevel:"WARN"})}(function(){i.log&&i.log.isStub&&(i.log.replay(function(a,b,g){var e=a[2]||{};e.t=b;e.r=g;e.n=1;n(a[0],a[1],e)}),i.onunload.replay(function(a){y.push(a[0])}),i.onflush.replay(function(a){w.push(a[0])}))})();i.log=n;i.log.reset=function(){C=0};i.onunload=function(a){y.push(a)};i.onflush=function(a){w.push(a)};
i.attach("beforeunload",h);i.attach("pagehide",h);d("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(a,c){function p(a){if(a)return a.replace(/^\s+|\s+$/g,"")}function m(b,o){if(!b)return{};b.m&&b.m.message&&(b=b.m);var e=o.m||o.message||"",e=b.m&&b.m.message?e+b.m.message:b.m&&b.m.target&&b.m.target.tagName?e+("Error handler invoked by "+b.m.target.tagName+" tag"):b.m?e+b.m:b.message?e+b.message:e+"Unknown error",e={m:e,f:b.f||b.sourceURL||b.fileName||b.filename||b.m&&b.m.target&&b.m.target.src,l:b.l||b.line||b.lineno||b.lineNumber,c:b.c?""+b.c:b.c,s:[],t:a.ue.d(),name:b.name,type:b.type,
csm:k+" "+(b.fromOnError?"onerror":"ueLogError")},i,c,f=0,j=0,m;i=b.stack||(b.err?b.err.stack:"");e.pageURL=o.pageURL||""+(window.location?window.location.href:"")||"missing";e.logLevel=o.logLevel||h;if(c=o.attribution)e.attribution=""+c;if(i&&i.split)for(e.csm+=" stack",c=i.split("\n");f<c.length&&e.s.length<d;)(i=c[f++])&&e.s.push(p(i));else for(e.csm+=" callee",c=l(b.args||arguments,"callee"),j=f=0;c&&f<d;)m=t,c.skipTrace||(i=c.toString())&&i.substr&&(m=0===j?4*t:m,m=1==j?2*t:m,e.s.push(i.substr(0,
m)),j++),c=l(c,"caller"),f++;if(!e.f&&0<e.s.length&&(f=e)&&f.s){var n;i=0<f.s.length?f.s[0]:"";c=1<f.s.length?f.s[1]:"";i&&(n=i.match(q));n&&3==n.length||!c||(n=c.match(s));n&&3==n.length&&(f.f=n[1],f.l=n[2])}return e}function l(a,o){try{return a[o]}catch(e){}}function j(b,o){if(b){var e=m(b,o);a.ue.log(e,o.channel||n,{nb:1});try{var i=c.console,k=c.JSON,d="Error logged: ";if(i){if(k&&k.stringify)try{d+=k.stringify(e)}catch(h){d+="no info provided; converting to string failed"}else d+=e.m;"function"===
typeof i.error?i.error(d,e):"function"===typeof i.log&&i.log(d,e)}}catch(f){}}}function f(b,o){if(b&&!(a.ue_err.ec>a.ue_err.mxe)){a.ue_err.ec++;a.ue_err.ter.push(b);var o=o||{},e=b.logLevel||o.logLevel;o.logLevel=e;o.attribution=b.attribution||o.attribution;e&&e!=h||ue_err.ecf++;j(b,o)}}if(!a.ueLogError||a.ueLogError.isStub){var n=a.ue_err_chan||"jserr",h="FATAL",k="v5",d=20,t=256,s=/\(?([^\s]*):(\d+):\d+\)?/,q=/.*@(.*):(\d*)/;j.skipTrace=1;m.skipTrace=1;f.skipTrace=1;(function(){if(a.ue_err.erl){var b=
a.ue_err.erl.length,o,e;for(o=0;o<b;o++)e=a.ue_err.erl[o],j(e.ex,e.info);ue_err.erl=[]}})();a.ueLogError=f}})(ue_csm,window);
(function(a,c){a.ue_cel||(a.ue_cel=function(){function p(a,o){o?o.r=s:o={r:s,c:1};o.clog&&k.clog?k.clog(a,n,o):o.glog&&k.glog?k.glog(a,n,o):k.log(a,n,o)}function m(){var a=j.length;if(0<a){for(var o=[],e=0;e<a;e++){var i=j[e].api;i.ready()?(i.on({ts:k.d,ns:n}),f.push(j[e]),p({k:"mso",n:j[e].name,t:k.d()})):o.push(j[e])}j=o}}function l(){if(!l.executed){for(var a=0;a<f.length;a++)f[a].api.off&&f[a].api.off({ts:k.d,ns:n});p({k:"eod",t0:k.t0,t:k.d()},{c:1});l.executed=1;for(a=0;a<f.length;a++)j.push(f[a]);
f=[];clearTimeout(h)}}var j=[],f=[],n=a.ue_cel_ns||"cel",h,k=a.ue,d=a.uet,t=a.uex,s=k.rid,q=c.requestAnimationFrame||function(a){a()};if(k.isBF)p({k:"bft",t:k.d()});else return"function"==typeof d&&d("bb","csmCELLSframework",{wb:1}),setTimeout(m,0),k.onunload(l),h=setTimeout(l,6E5),"function"==typeof t&&t("ld","csmCELLSframework",{wb:1}),{registerModule:function(a,o){j.push({name:a,api:o});p({k:"mrg",n:a,t:k.d()});m()},reset:function(a){p({k:"rst",t0:k.t0,t:k.d()});j=j.concat(f);f=[];for(var o=j.length,
e=0;e<o;e++)j[e].api.off(),j[e].api.reset();s=a||k.rid;m();clearTimeout(h);h=setTimeout(l,6E5);l.executed=0},timeout:function(a,o){return c.setTimeout(function(){q(a)},o)},log:p}}())})(ue_csm,window);
(function(a,c,p){a.ue_pdm||ue.isBF||(a.ue_pdm=function(){function m(){var b={w:f.width,aw:f.availWidth,h:f.height,ah:f.availHeight,cd:f.colorDepth,pd:f.pixelDepth},i={w:p.body.scrollWidth,h:p.body.scrollHeight};d&&d.w==b.w&&d.h==b.h&&d.aw==b.aw&&d.ah==b.ah&&d.pd==b.pd&&d.cd==b.cd||(d=b,d.t=h(),d.k="sci",q(d));t&&t.w==i.w&&t.h==i.h||(t=i,t.t=h(),t.k="doi",q(t));n=a.ue_cel.timeout(m,k)}function l(){q({k:"ebl",t:h()})}function j(){q({k:"efo",t:h()})}var f,n,h,k,d,t,s=a.ue,q=a.ue_cel.log,b=a.uet,o=a.uex;
"function"==typeof b&&b("bb","csmCELLSpdm",{wb:1});return{on:function(b){k=b.timespan||500;h=b.ts;f=c.screen;s.attach&&(s.attach("blur",l,c),s.attach("focus",j,c));b=c.location;q({k:"pmd",o:b.origin,p:b.pathname,t:h()});a.ue_cel.timeout(m,0);"function"==typeof o&&o("ld","csmCELLSpdm",{wb:1})},off:function(){clearTimeout(n);s.detach&&(s.detach("blur",l,c),s.detach("focus",j,c));s.count&&(s.count("cel.PDM.TotalExecutions",0),s.count("cel.PDM.TotalExecutionTime",0),s.count("cel.PDM.AverageExecutionTime",
0/0))},ready:function(){return p.body&&a.ue_cel&&a.ue_cel.log},reset:function(){d=t=null}}}(),a.ue_cel&&a.ue_cel.registerModule("page module",a.ue_pdm))})(ue_csm,window,document);
(function(a,c){a.ue_vpm||ue.isBF||(a.ue_vpm=function(){function p(){var a=n(),b={w:c.innerWidth,h:c.innerHeight,x:c.pageXOffset,y:c.pageYOffset};l&&l.w==b.w&&l.h==b.h&&l.x==b.x&&l.y==b.y||(b.t=a,b.k="vpi",l=b,t(l,{clog:1}));j=0;h=n()-a;k+=1}function m(){j||(j=a.ue_cel.timeout(p,f))}var l,j,f,n,h=0,k=0,d=a.ue,t=a.ue_cel.log,s=a.uet,q=a.uex,b=d.attach,o=d.detach;"function"==typeof s&&s("bb","csmCELLSvpm",{wb:1});return{on:function(e){n=e.ts;f=e.timespan||100;a.ue_cel.timeout(p,0);b&&(b("scroll",m),
b("resize",m));"function"==typeof q&&q("ld","csmCELLSvpm",{wb:1})},off:function(){clearTimeout(j);o&&(o("scroll",m),o("resize",m));d.count&&(d.count("cel.VPI.TotalExecutions",k),d.count("cel.VPI.TotalExecutionTime",h),d.count("cel.VPI.AverageExecutionTime",h/k))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){l=void 0},getVpi:function(){return l}}}(),a.ue_cel&&a.ue_cel.registerModule("viewport module",a.ue_vpm))})(ue_csm,window);
(function(a,c,p){var m=a.ue||{};!m.isBF&&!a.ue_fem&&p.querySelector&&c.getComputedStyle&&[].forEach&&(a.ue_fem=function(){function l(){a.ue_cel.timeout(function(){e.splice(0).forEach(function(a){i(a,{clog:1})})},0)}function j(a){for(var I={x:c.pageXOffset,y:c.pageYOffset},K=0;K<b.length;K++){var g=b[K];if(g.w&&g.w.length)for(var u=0;u<g.w.length;u++){var i=g.w[u],o;a:{try{var k=i,d=I;if(k){var h=k.getBoundingClientRect();o={x:h.left+d.x|0,y:h.top+d.y|0,w:h.width|0,h:h.height|0,d:(0===k.offsetWidth&&
0===k.offsetHeight)|0}}else o=void 0;break a}catch(f){}o=void 0}if(o&&!i.cel_b)i.cel_b=o,e.push({n:i.cel_n,w:i.cel_b.w,h:i.cel_b.h,d:i.cel_b.d,x:i.cel_b.x,y:i.cel_b.y,t:a,k:"ewi",cl:i.className});else{if(k=o)k=i.cel_b,d=o,k=d.d===k.d&&1===d.d?!1:!((k.x>d.x?3>k.x-d.x:3>d.x-k.x)&&(k.y>d.y?3>k.y-d.y:3>d.y-k.y)&&(k.w>d.w?3>k.w-d.w:3>d.w-k.w)&&(k.h>d.h?3>k.h-d.h:3>d.h-k.h)&&k.d===d.d);k&&(i.cel_b=o,e.push({n:i.cel_n,w:i.cel_b.w,h:i.cel_b.h,d:i.cel_b.d,x:i.cel_b.x,y:i.cel_b.y,t:a,k:"ewi"}))}}}}function f(a){for(var I=
0;I<b.length;I++){var i=b[I],g;g=i;g=g.c?p.getElementsByClassName(g.c):g.id?[p.getElementById(g.id)]:p.querySelectorAll(g.s);var u=i.w||[],M;for(M=0;M<u.length;M++){var c=u[M];r.contains(c)||e.push({n:c.cel_n,t:a,k:"ewd"})}i.w=[];for(M=0;M<g.length;M++)if(u=g[M])u.cel_n||(u.cel_n=u.getAttribute("cel_widget_id")||(i.id_gen||o)(u,M)||u.id),i.w.push(u)}h()}function n(){B||(B=a.ue_cel.timeout(function(){B=null;k("dwe",f);l()},d))}function h(){B||H||(H=a.ue_cel.timeout(function(){H=null;k("dwpc",j);l()},
d))}function k(a,b){var i=q();b(i);var g=q(),i=g-i;i<=t?g=0:g-E>=s?(E=g,g=0):(ue_fem.off(),g=1);(e.length||g)&&e.push({k:"ewt",e:a,d:i,ex:g,t:q()})}var d=50,t=10,s=3E3,q,b=[],o=function(){},e=[],i=a.ue_cel.log,r,v,y,w,x=c.MutationObserver||c.WebKitMutationObserver||c.MozMutationObserver,F=!!x,A,z,J="DOMAttrModified",G="DOMNodeInserted",C="DOMNodeRemoved",H,B,E=-s;"function"==typeof uet&&uet("bb","csmCELLSfem",{wb:1});return{on:function(e){function I(){if(y&&w&&r&&r.contains&&r.getBoundingClientRect&&
q){if(F){var a={attributes:!0,subtree:!0};A=new x(h);z=new x(n);A.observe(r,a);z.observe(r,{childList:!0,subtree:!0});z.observe(v,a)}else y.call(r,J,h),y.call(r,G,n),y.call(r,C,n),y.call(v,G,h),y.call(v,C,h);n()}}r=p.body;v=p.head;y=r.addEventListener;w=r.removeEventListener;q=e.ts;b=a.cel_widgets||[];m.deffered?I():m.attach&&m.attach("load",I);"function"==typeof uex&&uex("ld","csmCELLSfem",{wb:1})},off:function(){y&&w&&r&&r.contains&&r.getBoundingClientRect&&q&&(z&&(z.disconnect(),z=null),A&&(A.disconnect(),
A=null),w.call(r,J,h),w.call(r,G,n),w.call(r,C,n),w.call(v,G,h),w.call(v,C,h))},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){b=a.cel_widgets||[]}}}(),a.ue_cel&&a.ue_fem&&a.ue_cel.registerModule("features module",a.ue_fem))})(ue_csm,window,document);
(function(a,c){a.ue_mcm||a.ue.isBF||(a.ue_mcm=function(){function p(a){if(a.id)return"//*[@id='"+a.id+"']";var c;c=1;var h;for(h=a.previousSibling;h;h=h.previousSibling)h.nodeName==a.nodeName&&(c+=1);h=a.nodeName;1!=c&&(h+="["+c+"]");a.parentNode&&(h=p(a.parentNode)+"/"+h);return h}function m(a){var d=a.srcElement||a.target||{},f={k:l,w:c.body.scrollWidth,h:c.body.scrollHeight,t:j(),x:a.pageX,y:a.pageY,p:p(d),n:d.nodeName,e:h};a.button&&(f.b=a.button);d.href&&(f.r=d.href);d.id&&(f.i=d.id);d.className&&
(f.c=d.className.split(/\s+/));n(f,{n:1,c:1})}var l="mcm",j,f=a.ue,n=a.ue_cel.log,h=a.ue_mce||"click";return{on:function(a){j=a.ts;f.attach&&f.attach(h,m,c)},off:function(){f.detach&&f.detach(h,m,c)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){}}}(),a.ue_cel&&a.ue_cel.registerModule("mouse click module",a.ue_mcm))})(ue_csm,document);
(function(a,c){a.ue_mmm||a.ue.isBF||(a.ue_mmm=function(p){function m(a,b){var e={x:a.pageX||a.x||0,y:a.pageY||a.y||0,t:k()};!b&&F&&(e.t-F.t<f||e.x==F.x&&e.y==F.y)||(F=e,y.push(e))}function l(){if(y.length){r=G.now();for(var a=0;a<y.length;a++){var c=y[a],k=a;A=y[x];z=c;var d=void 0;if(!(d=2>k)){a:if(y[k].t-y[k-1].t>j)d=0;else{for(d=x+1;d<k;d++){var f=A,I=z,K=y[d];J=(I.x-f.x)*(f.y-K.y)-(f.x-K.x)*(I.y-f.y);if(J*J/((I.x-f.x)*(I.x-f.x)+(I.y-f.y)*(I.y-f.y))>n){d=0;break a}}d=1}d=!d}d?x=k-1:w.pop();w.push(c)}v=
G.now()-r;b=Math.min(b,v);o=Math.max(o,v);e=(e*i+v)/(i+1);i+=1;s({k:h,e:w,min:Math.floor(1E3*b),max:Math.floor(1E3*o),avg:Math.floor(1E3*e)},{c:1});y=[];w=[];x=0}}var j=100,f=20,n=25,h="mmm1",k,d,t=a.ue,s=a.ue_cel.log,q,b=1E3,o=0,e=0,i=0,r,v,y=[],w=[],x=0,F,A,z,J,G=p&&p.now&&p||Date.now&&Date||{now:function(){return(new Date).getTime()}};return{on:function(a){k=a.ts;d=a.ns;t.attach&&t.attach("mousemove",m,c);q=setInterval(l,3E3)},off:function(){d&&(F&&m(F,!0),l());clearInterval(q);t.detach&&t.detach("mousemove",
m,c)},ready:function(){return a.ue_cel&&a.ue_cel.log},reset:function(){y=[];w=[];x=0;F=null}}}(window.performance),a.ue_cel&&a.ue_cel.registerModule("mouse move module",a.ue_mmm))})(ue_csm,document);